/*
 * CrispHive Developer API
 * Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.crisphive.client.model.CustomerTierProgress;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * CustomerSpending
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class CustomerSpending {
  public static final String SERIALIZED_NAME_AVG_JOB_VALUE = "avg_job_value";
  @SerializedName(SERIALIZED_NAME_AVG_JOB_VALUE)
  @javax.annotation.Nullable
  private BigDecimal avgJobValue;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nullable
  private String currency;

  public static final String SERIALIZED_NAME_RANK_POSITION_LABEL = "rank_position_label";
  @SerializedName(SERIALIZED_NAME_RANK_POSITION_LABEL)
  @javax.annotation.Nullable
  private String rankPositionLabel;

  /**
   * Loyalty tier the spend resolves to.
   */
  @JsonAdapter(TierEnum.Adapter.class)
  public enum TierEnum {
    REGULAR("regular"),
    
    VIP("vip");

    private String value;

    TierEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TierEnum fromValue(String value) {
      for (TierEnum b : TierEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TierEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TierEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TierEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TierEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TierEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TIER = "tier";
  @SerializedName(SERIALIZED_NAME_TIER)
  @javax.annotation.Nullable
  private TierEnum tier;

  public static final String SERIALIZED_NAME_TIER_PROGRESS = "tier_progress";
  @SerializedName(SERIALIZED_NAME_TIER_PROGRESS)
  @javax.annotation.Nullable
  private CustomerTierProgress tierProgress;

  public static final String SERIALIZED_NAME_TOTAL_SPENT12M = "total_spent_12m";
  @SerializedName(SERIALIZED_NAME_TOTAL_SPENT12M)
  @javax.annotation.Nullable
  private BigDecimal totalSpent12m;

  public CustomerSpending() {
  }

  public CustomerSpending avgJobValue(@javax.annotation.Nullable BigDecimal avgJobValue) {
    this.avgJobValue = avgJobValue;
    return this;
  }

  /**
   * Average value per completed job.
   * @return avgJobValue
   */
  @javax.annotation.Nullable
  public BigDecimal getAvgJobValue() {
    return avgJobValue;
  }

  public void setAvgJobValue(@javax.annotation.Nullable BigDecimal avgJobValue) {
    this.avgJobValue = avgJobValue;
  }


  public CustomerSpending currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * ISO 4217 currency code for the monetary fields (e.g. \&quot;USD\&quot;, \&quot;CAD\&quot;).
   * @return currency
   */
  @javax.annotation.Nullable
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public CustomerSpending rankPositionLabel(@javax.annotation.Nullable String rankPositionLabel) {
    this.rankPositionLabel = rankPositionLabel;
    return this;
  }

  /**
   * Human-readable rank label (e.g. \&quot;Top 5%\&quot;).
   * @return rankPositionLabel
   */
  @javax.annotation.Nullable
  public String getRankPositionLabel() {
    return rankPositionLabel;
  }

  public void setRankPositionLabel(@javax.annotation.Nullable String rankPositionLabel) {
    this.rankPositionLabel = rankPositionLabel;
  }


  public CustomerSpending tier(@javax.annotation.Nullable TierEnum tier) {
    this.tier = tier;
    return this;
  }

  /**
   * Loyalty tier the spend resolves to.
   * @return tier
   */
  @javax.annotation.Nullable
  public TierEnum getTier() {
    return tier;
  }

  public void setTier(@javax.annotation.Nullable TierEnum tier) {
    this.tier = tier;
  }


  public CustomerSpending tierProgress(@javax.annotation.Nullable CustomerTierProgress tierProgress) {
    this.tierProgress = tierProgress;
    return this;
  }

  /**
   * Progress toward the next tier.
   * @return tierProgress
   */
  @javax.annotation.Nullable
  public CustomerTierProgress getTierProgress() {
    return tierProgress;
  }

  public void setTierProgress(@javax.annotation.Nullable CustomerTierProgress tierProgress) {
    this.tierProgress = tierProgress;
  }


  public CustomerSpending totalSpent12m(@javax.annotation.Nullable BigDecimal totalSpent12m) {
    this.totalSpent12m = totalSpent12m;
    return this;
  }

  /**
   * Total amount spent in the trailing 12 months.
   * @return totalSpent12m
   */
  @javax.annotation.Nullable
  public BigDecimal getTotalSpent12m() {
    return totalSpent12m;
  }

  public void setTotalSpent12m(@javax.annotation.Nullable BigDecimal totalSpent12m) {
    this.totalSpent12m = totalSpent12m;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerSpending customerSpending = (CustomerSpending) o;
    return Objects.equals(this.avgJobValue, customerSpending.avgJobValue) &&
        Objects.equals(this.currency, customerSpending.currency) &&
        Objects.equals(this.rankPositionLabel, customerSpending.rankPositionLabel) &&
        Objects.equals(this.tier, customerSpending.tier) &&
        Objects.equals(this.tierProgress, customerSpending.tierProgress) &&
        Objects.equals(this.totalSpent12m, customerSpending.totalSpent12m);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avgJobValue, currency, rankPositionLabel, tier, tierProgress, totalSpent12m);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerSpending {\n");
    sb.append("    avgJobValue: ").append(toIndentedString(avgJobValue)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    rankPositionLabel: ").append(toIndentedString(rankPositionLabel)).append("\n");
    sb.append("    tier: ").append(toIndentedString(tier)).append("\n");
    sb.append("    tierProgress: ").append(toIndentedString(tierProgress)).append("\n");
    sb.append("    totalSpent12m: ").append(toIndentedString(totalSpent12m)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("avg_job_value");
    openapiFields.add("currency");
    openapiFields.add("rank_position_label");
    openapiFields.add("tier");
    openapiFields.add("tier_progress");
    openapiFields.add("total_spent_12m");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CustomerSpending
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CustomerSpending.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CustomerSpending is not found in the empty JSON string", CustomerSpending.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CustomerSpending.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CustomerSpending` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) && !jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      if ((jsonObj.get("rank_position_label") != null && !jsonObj.get("rank_position_label").isJsonNull()) && !jsonObj.get("rank_position_label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rank_position_label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rank_position_label").toString()));
      }
      if ((jsonObj.get("tier") != null && !jsonObj.get("tier").isJsonNull()) && !jsonObj.get("tier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tier").toString()));
      }
      // validate the optional field `tier`
      if (jsonObj.get("tier") != null && !jsonObj.get("tier").isJsonNull()) {
        TierEnum.validateJsonElement(jsonObj.get("tier"));
      }
      // validate the optional field `tier_progress`
      if (jsonObj.get("tier_progress") != null && !jsonObj.get("tier_progress").isJsonNull()) {
        CustomerTierProgress.validateJsonElement(jsonObj.get("tier_progress"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustomerSpending.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustomerSpending' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustomerSpending> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustomerSpending.class));

       return (TypeAdapter<T>) new TypeAdapter<CustomerSpending>() {
           @Override
           public void write(JsonWriter out, CustomerSpending value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CustomerSpending read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CustomerSpending given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CustomerSpending
   * @throws IOException if the JSON string is invalid with respect to CustomerSpending
   */
  public static CustomerSpending fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustomerSpending.class);
  }

  /**
   * Convert an instance of CustomerSpending to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

