/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.crisphive.client.model.CustomerAddress;
import com.crisphive.client.model.ServiceArea;
import com.crisphive.client.model.Technician;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * CustomerContact
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class CustomerContact {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  @javax.annotation.Nullable
  private CustomerAddress address;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  @javax.annotation.Nullable
  private String phone;

  public static final String SERIALIZED_NAME_PREFERRED_TECHNICIAN = "preferred_technician";
  @SerializedName(SERIALIZED_NAME_PREFERRED_TECHNICIAN)
  @javax.annotation.Nullable
  private Technician preferredTechnician;

  public static final String SERIALIZED_NAME_SERVICE_AREA = "service_area";
  @SerializedName(SERIALIZED_NAME_SERVICE_AREA)
  @javax.annotation.Nullable
  private ServiceArea serviceArea;

  public CustomerContact() {
  }

  public CustomerContact address(@javax.annotation.Nullable CustomerAddress address) {
    this.address = address;
    return this;
  }

  /**
   * Postal address and coordinates.
   * @return address
   */
  @javax.annotation.Nullable
  public CustomerAddress getAddress() {
    return address;
  }

  public void setAddress(@javax.annotation.Nullable CustomerAddress address) {
    this.address = address;
  }


  public CustomerContact email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Email address.
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public CustomerContact phone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * Phone number in the form it was supplied.
   * @return phone
   */
  @javax.annotation.Nullable
  public String getPhone() {
    return phone;
  }

  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }


  public CustomerContact preferredTechnician(@javax.annotation.Nullable Technician preferredTechnician) {
    this.preferredTechnician = preferredTechnician;
    return this;
  }

  /**
   * The technician this customer prefers, if one is set; otherwise null.
   * @return preferredTechnician
   */
  @javax.annotation.Nullable
  public Technician getPreferredTechnician() {
    return preferredTechnician;
  }

  public void setPreferredTechnician(@javax.annotation.Nullable Technician preferredTechnician) {
    this.preferredTechnician = preferredTechnician;
  }


  public CustomerContact serviceArea(@javax.annotation.Nullable ServiceArea serviceArea) {
    this.serviceArea = serviceArea;
    return this;
  }

  /**
   * The service area this customer falls in, if resolved; otherwise null.
   * @return serviceArea
   */
  @javax.annotation.Nullable
  public ServiceArea getServiceArea() {
    return serviceArea;
  }

  public void setServiceArea(@javax.annotation.Nullable ServiceArea serviceArea) {
    this.serviceArea = serviceArea;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerContact customerContact = (CustomerContact) o;
    return Objects.equals(this.address, customerContact.address) &&
        Objects.equals(this.email, customerContact.email) &&
        Objects.equals(this.phone, customerContact.phone) &&
        Objects.equals(this.preferredTechnician, customerContact.preferredTechnician) &&
        Objects.equals(this.serviceArea, customerContact.serviceArea);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, email, phone, preferredTechnician, serviceArea);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerContact {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    preferredTechnician: ").append(toIndentedString(preferredTechnician)).append("\n");
    sb.append("    serviceArea: ").append(toIndentedString(serviceArea)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("address");
    openapiFields.add("email");
    openapiFields.add("phone");
    openapiFields.add("preferred_technician");
    openapiFields.add("service_area");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CustomerContact
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CustomerContact.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CustomerContact is not found in the empty JSON string", CustomerContact.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CustomerContact.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CustomerContact` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `address`
      if (jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) {
        CustomerAddress.validateJsonElement(jsonObj.get("address"));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("phone") != null && !jsonObj.get("phone").isJsonNull()) && !jsonObj.get("phone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `phone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phone").toString()));
      }
      // validate the optional field `preferred_technician`
      if (jsonObj.get("preferred_technician") != null && !jsonObj.get("preferred_technician").isJsonNull()) {
        Technician.validateJsonElement(jsonObj.get("preferred_technician"));
      }
      // validate the optional field `service_area`
      if (jsonObj.get("service_area") != null && !jsonObj.get("service_area").isJsonNull()) {
        ServiceArea.validateJsonElement(jsonObj.get("service_area"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustomerContact.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustomerContact' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustomerContact> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustomerContact.class));

       return (TypeAdapter<T>) new TypeAdapter<CustomerContact>() {
           @Override
           public void write(JsonWriter out, CustomerContact value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CustomerContact read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CustomerContact given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CustomerContact
   * @throws IOException if the JSON string is invalid with respect to CustomerContact
   */
  public static CustomerContact fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustomerContact.class);
  }

  /**
   * Convert an instance of CustomerContact to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

