/*
 * CrispHive Developer API
 * Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.crisphive.client.model.JobDatePeriod;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * JobDateBusinessRange
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class JobDateBusinessRange {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime date;

  public static final String SERIALIZED_NAME_END_MINUTE = "end_minute";
  @SerializedName(SERIALIZED_NAME_END_MINUTE)
  @javax.annotation.Nullable
  private Integer endMinute;

  public static final String SERIALIZED_NAME_PERIOD = "period";
  @SerializedName(SERIALIZED_NAME_PERIOD)
  @javax.annotation.Nullable
  private JobDatePeriod period;

  public static final String SERIALIZED_NAME_START_MINUTE = "start_minute";
  @SerializedName(SERIALIZED_NAME_START_MINUTE)
  @javax.annotation.Nullable
  private Integer startMinute;

  public JobDateBusinessRange() {
  }

  public JobDateBusinessRange date(@javax.annotation.Nullable OffsetDateTime date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(@javax.annotation.Nullable OffsetDateTime date) {
    this.date = date;
  }


  public JobDateBusinessRange endMinute(@javax.annotation.Nullable Integer endMinute) {
    this.endMinute = endMinute;
    return this;
  }

  /**
   * Get endMinute
   * @return endMinute
   */
  @javax.annotation.Nullable
  public Integer getEndMinute() {
    return endMinute;
  }

  public void setEndMinute(@javax.annotation.Nullable Integer endMinute) {
    this.endMinute = endMinute;
  }


  public JobDateBusinessRange period(@javax.annotation.Nullable JobDatePeriod period) {
    this.period = period;
    return this;
  }

  /**
   * Get period
   * @return period
   */
  @javax.annotation.Nullable
  public JobDatePeriod getPeriod() {
    return period;
  }

  public void setPeriod(@javax.annotation.Nullable JobDatePeriod period) {
    this.period = period;
  }


  public JobDateBusinessRange startMinute(@javax.annotation.Nullable Integer startMinute) {
    this.startMinute = startMinute;
    return this;
  }

  /**
   * Get startMinute
   * @return startMinute
   */
  @javax.annotation.Nullable
  public Integer getStartMinute() {
    return startMinute;
  }

  public void setStartMinute(@javax.annotation.Nullable Integer startMinute) {
    this.startMinute = startMinute;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobDateBusinessRange jobDateBusinessRange = (JobDateBusinessRange) o;
    return Objects.equals(this.date, jobDateBusinessRange.date) &&
        Objects.equals(this.endMinute, jobDateBusinessRange.endMinute) &&
        Objects.equals(this.period, jobDateBusinessRange.period) &&
        Objects.equals(this.startMinute, jobDateBusinessRange.startMinute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, endMinute, period, startMinute);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobDateBusinessRange {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    endMinute: ").append(toIndentedString(endMinute)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    startMinute: ").append(toIndentedString(startMinute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("date");
    openapiFields.add("end_minute");
    openapiFields.add("period");
    openapiFields.add("start_minute");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobDateBusinessRange
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobDateBusinessRange.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobDateBusinessRange is not found in the empty JSON string", JobDateBusinessRange.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobDateBusinessRange.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JobDateBusinessRange` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `period`
      if (jsonObj.get("period") != null && !jsonObj.get("period").isJsonNull()) {
        JobDatePeriod.validateJsonElement(jsonObj.get("period"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobDateBusinessRange.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobDateBusinessRange' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobDateBusinessRange> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobDateBusinessRange.class));

       return (TypeAdapter<T>) new TypeAdapter<JobDateBusinessRange>() {
           @Override
           public void write(JsonWriter out, JobDateBusinessRange value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobDateBusinessRange read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobDateBusinessRange given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobDateBusinessRange
   * @throws IOException if the JSON string is invalid with respect to JobDateBusinessRange
   */
  public static JobDateBusinessRange fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobDateBusinessRange.class);
  }

  /**
   * Convert an instance of JobDateBusinessRange to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

