/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.crisphive.client.model.JobDateBusinessRange;
import com.crisphive.client.model.JobDatePeriod;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * JobDatePeriodEntry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class JobDatePeriodEntry {
  public static final String SERIALIZED_NAME_BUSINESS_VIEW = "business_view";
  @SerializedName(SERIALIZED_NAME_BUSINESS_VIEW)
  @javax.annotation.Nullable
  private List<JobDateBusinessRange> businessView = new ArrayList<>();

  public static final String SERIALIZED_NAME_PERIOD = "period";
  @SerializedName(SERIALIZED_NAME_PERIOD)
  @javax.annotation.Nullable
  private JobDatePeriod period;

  public JobDatePeriodEntry() {
  }

  public JobDatePeriodEntry businessView(@javax.annotation.Nullable List<JobDateBusinessRange> businessView) {
    this.businessView = businessView;
    return this;
  }

  public JobDatePeriodEntry addBusinessViewItem(JobDateBusinessRange businessViewItem) {
    if (this.businessView == null) {
      this.businessView = new ArrayList<>();
    }
    this.businessView.add(businessViewItem);
    return this;
  }

  /**
   * Business-local minute ranges that back this period selection.
   * @return businessView
   */
  @javax.annotation.Nullable
  public List<JobDateBusinessRange> getBusinessView() {
    return businessView;
  }

  public void setBusinessView(@javax.annotation.Nullable List<JobDateBusinessRange> businessView) {
    this.businessView = businessView;
  }


  public JobDatePeriodEntry period(@javax.annotation.Nullable JobDatePeriod period) {
    this.period = period;
    return this;
  }

  /**
   * Time-of-day period the customer picked.
   * @return period
   */
  @javax.annotation.Nullable
  public JobDatePeriod getPeriod() {
    return period;
  }

  public void setPeriod(@javax.annotation.Nullable JobDatePeriod period) {
    this.period = period;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobDatePeriodEntry jobDatePeriodEntry = (JobDatePeriodEntry) o;
    return Objects.equals(this.businessView, jobDatePeriodEntry.businessView) &&
        Objects.equals(this.period, jobDatePeriodEntry.period);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessView, period);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobDatePeriodEntry {\n");
    sb.append("    businessView: ").append(toIndentedString(businessView)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("business_view");
    openapiFields.add("period");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobDatePeriodEntry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobDatePeriodEntry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobDatePeriodEntry is not found in the empty JSON string", JobDatePeriodEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobDatePeriodEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JobDatePeriodEntry` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("business_view") != null && !jsonObj.get("business_view").isJsonNull()) {
        JsonArray jsonArraybusinessView = jsonObj.getAsJsonArray("business_view");
        if (jsonArraybusinessView != null) {
          // ensure the json data is an array
          if (!jsonObj.get("business_view").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `business_view` to be an array in the JSON string but got `%s`", jsonObj.get("business_view").toString()));
          }

          // validate the optional field `business_view` (array)
          for (int i = 0; i < jsonArraybusinessView.size(); i++) {
            JobDateBusinessRange.validateJsonElement(jsonArraybusinessView.get(i));
          };
        }
      }
      // validate the optional field `period`
      if (jsonObj.get("period") != null && !jsonObj.get("period").isJsonNull()) {
        JobDatePeriod.validateJsonElement(jsonObj.get("period"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobDatePeriodEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobDatePeriodEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobDatePeriodEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobDatePeriodEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<JobDatePeriodEntry>() {
           @Override
           public void write(JsonWriter out, JobDatePeriodEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobDatePeriodEntry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobDatePeriodEntry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobDatePeriodEntry
   * @throws IOException if the JSON string is invalid with respect to JobDatePeriodEntry
   */
  public static JobDatePeriodEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobDatePeriodEntry.class);
  }

  /**
   * Convert an instance of JobDatePeriodEntry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

