/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * JobRequestTimeSegmentsBusinessTime
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class JobRequestTimeSegmentsBusinessTime {
  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  @javax.annotation.Nullable
  private LocalDate date;

  public static final String SERIALIZED_NAME_DATETIME = "datetime";
  @SerializedName(SERIALIZED_NAME_DATETIME)
  @javax.annotation.Nullable
  private String datetime;

  public static final String SERIALIZED_NAME_DAY_NAME = "day_name";
  @SerializedName(SERIALIZED_NAME_DAY_NAME)
  @javax.annotation.Nullable
  private String dayName;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  @javax.annotation.Nullable
  private String time;

  public static final String SERIALIZED_NAME_TIME_END = "time_end";
  @SerializedName(SERIALIZED_NAME_TIME_END)
  @javax.annotation.Nullable
  private String timeEnd;

  /**
   * Period bucket of the window start, business-local: 1&#x3D;morning, 2&#x3D;afternoon, 3&#x3D;evening.
   */
  @JsonAdapter(TimePeriodEnum.Adapter.class)
  public enum TimePeriodEnum {
    NUMBER_1(1),
    
    NUMBER_2(2),
    
    NUMBER_3(3);

    private Integer value;

    TimePeriodEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TimePeriodEnum fromValue(Integer value) {
      for (TimePeriodEnum b : TimePeriodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TimePeriodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TimePeriodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TimePeriodEnum read(final JsonReader jsonReader) throws IOException {
        Integer value =  jsonReader.nextInt();
        return TimePeriodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      Integer value = jsonElement.getAsInt();
      TimePeriodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TIME_PERIOD = "time_period";
  @SerializedName(SERIALIZED_NAME_TIME_PERIOD)
  @javax.annotation.Nullable
  private TimePeriodEnum timePeriod;

  /**
   * Localized label for time_period.
   */
  @JsonAdapter(TimePeriodLabelEnum.Adapter.class)
  public enum TimePeriodLabelEnum {
    MORNING("Morning"),
    
    AFTERNOON("Afternoon"),
    
    EVENING("Evening");

    private String value;

    TimePeriodLabelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TimePeriodLabelEnum fromValue(String value) {
      for (TimePeriodLabelEnum b : TimePeriodLabelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TimePeriodLabelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TimePeriodLabelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TimePeriodLabelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TimePeriodLabelEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TimePeriodLabelEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TIME_PERIOD_LABEL = "time_period_label";
  @SerializedName(SERIALIZED_NAME_TIME_PERIOD_LABEL)
  @javax.annotation.Nullable
  private TimePeriodLabelEnum timePeriodLabel;

  public JobRequestTimeSegmentsBusinessTime() {
  }

  public JobRequestTimeSegmentsBusinessTime date(@javax.annotation.Nullable LocalDate date) {
    this.date = date;
    return this;
  }

  /**
   * Calendar day of the window start, business-local (YYYY-MM-DD).
   * @return date
   */
  @javax.annotation.Nullable
  public LocalDate getDate() {
    return date;
  }

  public void setDate(@javax.annotation.Nullable LocalDate date) {
    this.date = date;
  }


  public JobRequestTimeSegmentsBusinessTime datetime(@javax.annotation.Nullable String datetime) {
    this.datetime = datetime;
    return this;
  }

  /**
   * Window start as a naive business-local datetime (no UTC offset) — the exact value to send back as scheduled_at on confirm.
   * @return datetime
   */
  @javax.annotation.Nullable
  public String getDatetime() {
    return datetime;
  }

  public void setDatetime(@javax.annotation.Nullable String datetime) {
    this.datetime = datetime;
  }


  public JobRequestTimeSegmentsBusinessTime dayName(@javax.annotation.Nullable String dayName) {
    this.dayName = dayName;
    return this;
  }

  /**
   * Full weekday name of the window start, business-local.
   * @return dayName
   */
  @javax.annotation.Nullable
  public String getDayName() {
    return dayName;
  }

  public void setDayName(@javax.annotation.Nullable String dayName) {
    this.dayName = dayName;
  }


  public JobRequestTimeSegmentsBusinessTime time(@javax.annotation.Nullable String time) {
    this.time = time;
    return this;
  }

  /**
   * Arrival-window start, HH:MM business-local.
   * @return time
   */
  @javax.annotation.Nullable
  public String getTime() {
    return time;
  }

  public void setTime(@javax.annotation.Nullable String time) {
    this.time = time;
  }


  public JobRequestTimeSegmentsBusinessTime timeEnd(@javax.annotation.Nullable String timeEnd) {
    this.timeEnd = timeEnd;
    return this;
  }

  /**
   * Arrival-window end, HH:MM business-local.
   * @return timeEnd
   */
  @javax.annotation.Nullable
  public String getTimeEnd() {
    return timeEnd;
  }

  public void setTimeEnd(@javax.annotation.Nullable String timeEnd) {
    this.timeEnd = timeEnd;
  }


  public JobRequestTimeSegmentsBusinessTime timePeriod(@javax.annotation.Nullable TimePeriodEnum timePeriod) {
    this.timePeriod = timePeriod;
    return this;
  }

  /**
   * Period bucket of the window start, business-local: 1&#x3D;morning, 2&#x3D;afternoon, 3&#x3D;evening.
   * @return timePeriod
   */
  @javax.annotation.Nullable
  public TimePeriodEnum getTimePeriod() {
    return timePeriod;
  }

  public void setTimePeriod(@javax.annotation.Nullable TimePeriodEnum timePeriod) {
    this.timePeriod = timePeriod;
  }


  public JobRequestTimeSegmentsBusinessTime timePeriodLabel(@javax.annotation.Nullable TimePeriodLabelEnum timePeriodLabel) {
    this.timePeriodLabel = timePeriodLabel;
    return this;
  }

  /**
   * Localized label for time_period.
   * @return timePeriodLabel
   */
  @javax.annotation.Nullable
  public TimePeriodLabelEnum getTimePeriodLabel() {
    return timePeriodLabel;
  }

  public void setTimePeriodLabel(@javax.annotation.Nullable TimePeriodLabelEnum timePeriodLabel) {
    this.timePeriodLabel = timePeriodLabel;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobRequestTimeSegmentsBusinessTime jobRequestTimeSegmentsBusinessTime = (JobRequestTimeSegmentsBusinessTime) o;
    return Objects.equals(this.date, jobRequestTimeSegmentsBusinessTime.date) &&
        Objects.equals(this.datetime, jobRequestTimeSegmentsBusinessTime.datetime) &&
        Objects.equals(this.dayName, jobRequestTimeSegmentsBusinessTime.dayName) &&
        Objects.equals(this.time, jobRequestTimeSegmentsBusinessTime.time) &&
        Objects.equals(this.timeEnd, jobRequestTimeSegmentsBusinessTime.timeEnd) &&
        Objects.equals(this.timePeriod, jobRequestTimeSegmentsBusinessTime.timePeriod) &&
        Objects.equals(this.timePeriodLabel, jobRequestTimeSegmentsBusinessTime.timePeriodLabel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, datetime, dayName, time, timeEnd, timePeriod, timePeriodLabel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobRequestTimeSegmentsBusinessTime {\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    datetime: ").append(toIndentedString(datetime)).append("\n");
    sb.append("    dayName: ").append(toIndentedString(dayName)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    timeEnd: ").append(toIndentedString(timeEnd)).append("\n");
    sb.append("    timePeriod: ").append(toIndentedString(timePeriod)).append("\n");
    sb.append("    timePeriodLabel: ").append(toIndentedString(timePeriodLabel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("date");
    openapiFields.add("datetime");
    openapiFields.add("day_name");
    openapiFields.add("time");
    openapiFields.add("time_end");
    openapiFields.add("time_period");
    openapiFields.add("time_period_label");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobRequestTimeSegmentsBusinessTime
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobRequestTimeSegmentsBusinessTime.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobRequestTimeSegmentsBusinessTime is not found in the empty JSON string", JobRequestTimeSegmentsBusinessTime.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobRequestTimeSegmentsBusinessTime.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JobRequestTimeSegmentsBusinessTime` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("datetime") != null && !jsonObj.get("datetime").isJsonNull()) && !jsonObj.get("datetime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `datetime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("datetime").toString()));
      }
      if ((jsonObj.get("day_name") != null && !jsonObj.get("day_name").isJsonNull()) && !jsonObj.get("day_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `day_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("day_name").toString()));
      }
      if ((jsonObj.get("time") != null && !jsonObj.get("time").isJsonNull()) && !jsonObj.get("time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("time").toString()));
      }
      if ((jsonObj.get("time_end") != null && !jsonObj.get("time_end").isJsonNull()) && !jsonObj.get("time_end").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `time_end` to be a primitive type in the JSON string but got `%s`", jsonObj.get("time_end").toString()));
      }
      // validate the optional field `time_period`
      if (jsonObj.get("time_period") != null && !jsonObj.get("time_period").isJsonNull()) {
        TimePeriodEnum.validateJsonElement(jsonObj.get("time_period"));
      }
      if ((jsonObj.get("time_period_label") != null && !jsonObj.get("time_period_label").isJsonNull()) && !jsonObj.get("time_period_label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `time_period_label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("time_period_label").toString()));
      }
      // validate the optional field `time_period_label`
      if (jsonObj.get("time_period_label") != null && !jsonObj.get("time_period_label").isJsonNull()) {
        TimePeriodLabelEnum.validateJsonElement(jsonObj.get("time_period_label"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobRequestTimeSegmentsBusinessTime.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobRequestTimeSegmentsBusinessTime' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobRequestTimeSegmentsBusinessTime> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobRequestTimeSegmentsBusinessTime.class));

       return (TypeAdapter<T>) new TypeAdapter<JobRequestTimeSegmentsBusinessTime>() {
           @Override
           public void write(JsonWriter out, JobRequestTimeSegmentsBusinessTime value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobRequestTimeSegmentsBusinessTime read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobRequestTimeSegmentsBusinessTime given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobRequestTimeSegmentsBusinessTime
   * @throws IOException if the JSON string is invalid with respect to JobRequestTimeSegmentsBusinessTime
   */
  public static JobRequestTimeSegmentsBusinessTime fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobRequestTimeSegmentsBusinessTime.class);
  }

  /**
   * Convert an instance of JobRequestTimeSegmentsBusinessTime to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

