/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.crisphive.client.model.JobRequestDayWindows;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * JobRequestBookingWindows
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class JobRequestBookingWindows {
  public static final String SERIALIZED_NAME_ALIAS = "alias";
  @SerializedName(SERIALIZED_NAME_ALIAS)
  @javax.annotation.Nullable
  private String alias;

  public static final String SERIALIZED_NAME_BUSINESS_TIMEZONE = "business_timezone";
  @SerializedName(SERIALIZED_NAME_BUSINESS_TIMEZONE)
  @javax.annotation.Nullable
  private String businessTimezone;

  public static final String SERIALIZED_NAME_CUSTOMER_TIMEZONE = "customer_timezone";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_TIMEZONE)
  @javax.annotation.Nullable
  private String customerTimezone;

  public static final String SERIALIZED_NAME_DAYS = "days";
  @SerializedName(SERIALIZED_NAME_DAYS)
  @javax.annotation.Nullable
  private List<JobRequestDayWindows> days = new ArrayList<>();

  public JobRequestBookingWindows() {
  }

  public JobRequestBookingWindows alias(@javax.annotation.Nullable String alias) {
    this.alias = alias;
    return this;
  }

  /**
   * Business alias the windows were computed for.
   * @return alias
   */
  @javax.annotation.Nullable
  public String getAlias() {
    return alias;
  }

  public void setAlias(@javax.annotation.Nullable String alias) {
    this.alias = alias;
  }


  public JobRequestBookingWindows businessTimezone(@javax.annotation.Nullable String businessTimezone) {
    this.businessTimezone = businessTimezone;
    return this;
  }

  /**
   * IANA timezone of the business (the business_view ranges).
   * @return businessTimezone
   */
  @javax.annotation.Nullable
  public String getBusinessTimezone() {
    return businessTimezone;
  }

  public void setBusinessTimezone(@javax.annotation.Nullable String businessTimezone) {
    this.businessTimezone = businessTimezone;
  }


  public JobRequestBookingWindows customerTimezone(@javax.annotation.Nullable String customerTimezone) {
    this.customerTimezone = customerTimezone;
    return this;
  }

  /**
   * IANA timezone the customer-facing dates/periods are expressed in.
   * @return customerTimezone
   */
  @javax.annotation.Nullable
  public String getCustomerTimezone() {
    return customerTimezone;
  }

  public void setCustomerTimezone(@javax.annotation.Nullable String customerTimezone) {
    this.customerTimezone = customerTimezone;
  }


  public JobRequestBookingWindows days(@javax.annotation.Nullable List<JobRequestDayWindows> days) {
    this.days = days;
    return this;
  }

  public JobRequestBookingWindows addDaysItem(JobRequestDayWindows daysItem) {
    if (this.days == null) {
      this.days = new ArrayList<>();
    }
    this.days.add(daysItem);
    return this;
  }

  /**
   * Per-day availability, ordered chronologically.
   * @return days
   */
  @javax.annotation.Nullable
  public List<JobRequestDayWindows> getDays() {
    return days;
  }

  public void setDays(@javax.annotation.Nullable List<JobRequestDayWindows> days) {
    this.days = days;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobRequestBookingWindows jobRequestBookingWindows = (JobRequestBookingWindows) o;
    return Objects.equals(this.alias, jobRequestBookingWindows.alias) &&
        Objects.equals(this.businessTimezone, jobRequestBookingWindows.businessTimezone) &&
        Objects.equals(this.customerTimezone, jobRequestBookingWindows.customerTimezone) &&
        Objects.equals(this.days, jobRequestBookingWindows.days);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alias, businessTimezone, customerTimezone, days);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobRequestBookingWindows {\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    businessTimezone: ").append(toIndentedString(businessTimezone)).append("\n");
    sb.append("    customerTimezone: ").append(toIndentedString(customerTimezone)).append("\n");
    sb.append("    days: ").append(toIndentedString(days)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("alias");
    openapiFields.add("business_timezone");
    openapiFields.add("customer_timezone");
    openapiFields.add("days");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobRequestBookingWindows
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobRequestBookingWindows.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobRequestBookingWindows is not found in the empty JSON string", JobRequestBookingWindows.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobRequestBookingWindows.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JobRequestBookingWindows` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("alias") != null && !jsonObj.get("alias").isJsonNull()) && !jsonObj.get("alias").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `alias` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alias").toString()));
      }
      if ((jsonObj.get("business_timezone") != null && !jsonObj.get("business_timezone").isJsonNull()) && !jsonObj.get("business_timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `business_timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("business_timezone").toString()));
      }
      if ((jsonObj.get("customer_timezone") != null && !jsonObj.get("customer_timezone").isJsonNull()) && !jsonObj.get("customer_timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customer_timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customer_timezone").toString()));
      }
      if (jsonObj.get("days") != null && !jsonObj.get("days").isJsonNull()) {
        JsonArray jsonArraydays = jsonObj.getAsJsonArray("days");
        if (jsonArraydays != null) {
          // ensure the json data is an array
          if (!jsonObj.get("days").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `days` to be an array in the JSON string but got `%s`", jsonObj.get("days").toString()));
          }

          // validate the optional field `days` (array)
          for (int i = 0; i < jsonArraydays.size(); i++) {
            JobRequestDayWindows.validateJsonElement(jsonArraydays.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobRequestBookingWindows.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobRequestBookingWindows' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobRequestBookingWindows> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobRequestBookingWindows.class));

       return (TypeAdapter<T>) new TypeAdapter<JobRequestBookingWindows>() {
           @Override
           public void write(JsonWriter out, JobRequestBookingWindows value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobRequestBookingWindows read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobRequestBookingWindows given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobRequestBookingWindows
   * @throws IOException if the JSON string is invalid with respect to JobRequestBookingWindows
   */
  public static JobRequestBookingWindows fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobRequestBookingWindows.class);
  }

  /**
   * Convert an instance of JobRequestBookingWindows to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

