/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.crisphive.client.model.JobRequestAbsenceAlternativeCost;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * JobRequestAbsenceAlternative
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class JobRequestAbsenceAlternative {
  public static final String SERIALIZED_NAME_COST = "cost";
  @SerializedName(SERIALIZED_NAME_COST)
  @javax.annotation.Nullable
  private JobRequestAbsenceAlternativeCost cost;

  public static final String SERIALIZED_NAME_DESIRED_SKILLS = "desired_skills";
  @SerializedName(SERIALIZED_NAME_DESIRED_SKILLS)
  @javax.annotation.Nullable
  private Integer desiredSkills;

  public static final String SERIALIZED_NAME_END_AT = "end_at";
  @SerializedName(SERIALIZED_NAME_END_AT)
  @javax.annotation.Nullable
  private OffsetDateTime endAt;

  public static final String SERIALIZED_NAME_FEASIBLE_COUNT = "feasible_count";
  @SerializedName(SERIALIZED_NAME_FEASIBLE_COUNT)
  @javax.annotation.Nullable
  private Integer feasibleCount;

  /**
   * What the option does to the customer&#39;s appointment. EXTEND-ONLY — carry a default branch. reassign_out_of_area keeps the window; reschedule_same_day / reschedule_later_day move it.
   */
  @JsonAdapter(KindEnum.Adapter.class)
  public enum KindEnum {
    REASSIGN_OUT_OF_AREA("reassign_out_of_area"),
    
    RESCHEDULE_SAME_DAY("reschedule_same_day"),
    
    RESCHEDULE_LATER_DAY("reschedule_later_day");

    private String value;

    KindEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static KindEnum fromValue(String value) {
      for (KindEnum b : KindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<KindEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final KindEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public KindEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return KindEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      KindEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  @javax.annotation.Nullable
  private KindEnum kind;

  public static final String SERIALIZED_NAME_MATCHED_SKILLS = "matched_skills";
  @SerializedName(SERIALIZED_NAME_MATCHED_SKILLS)
  @javax.annotation.Nullable
  private Integer matchedSkills;

  public static final String SERIALIZED_NAME_START_AT = "start_at";
  @SerializedName(SERIALIZED_NAME_START_AT)
  @javax.annotation.Nullable
  private OffsetDateTime startAt;

  public static final String SERIALIZED_NAME_STATUS_VERSION = "status_version";
  @SerializedName(SERIALIZED_NAME_STATUS_VERSION)
  @javax.annotation.Nullable
  private Integer statusVersion;

  public static final String SERIALIZED_NAME_TO_NAME = "to_name";
  @SerializedName(SERIALIZED_NAME_TO_NAME)
  @javax.annotation.Nullable
  private String toName;

  public static final String SERIALIZED_NAME_TO_TECHNICIAN_ID = "to_technician_id";
  @SerializedName(SERIALIZED_NAME_TO_TECHNICIAN_ID)
  @javax.annotation.Nullable
  private UUID toTechnicianId;

  public static final String SERIALIZED_NAME_TOTAL_SCORE = "total_score";
  @SerializedName(SERIALIZED_NAME_TOTAL_SCORE)
  @javax.annotation.Nullable
  private BigDecimal totalScore;

  public static final String SERIALIZED_NAME_WINDOW_MOVED = "window_moved";
  @SerializedName(SERIALIZED_NAME_WINDOW_MOVED)
  @javax.annotation.Nullable
  private Boolean windowMoved;

  public JobRequestAbsenceAlternative() {
  }

  public JobRequestAbsenceAlternative cost(@javax.annotation.Nullable JobRequestAbsenceAlternativeCost cost) {
    this.cost = cost;
    return this;
  }

  /**
   * What accepting it costs.
   * @return cost
   */
  @javax.annotation.Nullable
  public JobRequestAbsenceAlternativeCost getCost() {
    return cost;
  }

  public void setCost(@javax.annotation.Nullable JobRequestAbsenceAlternativeCost cost) {
    this.cost = cost;
  }


  public JobRequestAbsenceAlternative desiredSkills(@javax.annotation.Nullable Integer desiredSkills) {
    this.desiredSkills = desiredSkills;
    return this;
  }

  /**
   * Get desiredSkills
   * @return desiredSkills
   */
  @javax.annotation.Nullable
  public Integer getDesiredSkills() {
    return desiredSkills;
  }

  public void setDesiredSkills(@javax.annotation.Nullable Integer desiredSkills) {
    this.desiredSkills = desiredSkills;
  }


  public JobRequestAbsenceAlternative endAt(@javax.annotation.Nullable OffsetDateTime endAt) {
    this.endAt = endAt;
    return this;
  }

  /**
   * Get endAt
   * @return endAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEndAt() {
    return endAt;
  }

  public void setEndAt(@javax.annotation.Nullable OffsetDateTime endAt) {
    this.endAt = endAt;
  }


  public JobRequestAbsenceAlternative feasibleCount(@javax.annotation.Nullable Integer feasibleCount) {
    this.feasibleCount = feasibleCount;
    return this;
  }

  /**
   * How many technicians the engine offered at that window under this option&#39;s relaxation.
   * @return feasibleCount
   */
  @javax.annotation.Nullable
  public Integer getFeasibleCount() {
    return feasibleCount;
  }

  public void setFeasibleCount(@javax.annotation.Nullable Integer feasibleCount) {
    this.feasibleCount = feasibleCount;
  }


  public JobRequestAbsenceAlternative kind(@javax.annotation.Nullable KindEnum kind) {
    this.kind = kind;
    return this;
  }

  /**
   * What the option does to the customer&#39;s appointment. EXTEND-ONLY — carry a default branch. reassign_out_of_area keeps the window; reschedule_same_day / reschedule_later_day move it.
   * @return kind
   */
  @javax.annotation.Nullable
  public KindEnum getKind() {
    return kind;
  }

  public void setKind(@javax.annotation.Nullable KindEnum kind) {
    this.kind = kind;
  }


  public JobRequestAbsenceAlternative matchedSkills(@javax.annotation.Nullable Integer matchedSkills) {
    this.matchedSkills = matchedSkills;
    return this;
  }

  /**
   * Desired skills the technician holds / the job asks for.
   * @return matchedSkills
   */
  @javax.annotation.Nullable
  public Integer getMatchedSkills() {
    return matchedSkills;
  }

  public void setMatchedSkills(@javax.annotation.Nullable Integer matchedSkills) {
    this.matchedSkills = matchedSkills;
  }


  public JobRequestAbsenceAlternative startAt(@javax.annotation.Nullable OffsetDateTime startAt) {
    this.startAt = startAt;
    return this;
  }

  /**
   * The window the job would run in (UTC) — unchanged for a reassign kind, new for a reschedule kind.
   * @return startAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getStartAt() {
    return startAt;
  }

  public void setStartAt(@javax.annotation.Nullable OffsetDateTime startAt) {
    this.startAt = startAt;
  }


  public JobRequestAbsenceAlternative statusVersion(@javax.annotation.Nullable Integer statusVersion) {
    this.statusVersion = statusVersion;
    return this;
  }

  /**
   * The job&#39;s current status_version — copy it onto the commit assignment (the drift fence).
   * @return statusVersion
   */
  @javax.annotation.Nullable
  public Integer getStatusVersion() {
    return statusVersion;
  }

  public void setStatusVersion(@javax.annotation.Nullable Integer statusVersion) {
    this.statusVersion = statusVersion;
  }


  public JobRequestAbsenceAlternative toName(@javax.annotation.Nullable String toName) {
    this.toName = toName;
    return this;
  }

  /**
   * Get toName
   * @return toName
   */
  @javax.annotation.Nullable
  public String getToName() {
    return toName;
  }

  public void setToName(@javax.annotation.Nullable String toName) {
    this.toName = toName;
  }


  public JobRequestAbsenceAlternative toTechnicianId(@javax.annotation.Nullable UUID toTechnicianId) {
    this.toTechnicianId = toTechnicianId;
    return this;
  }

  /**
   * UUID + full name of the technician who would take the job.
   * @return toTechnicianId
   */
  @javax.annotation.Nullable
  public UUID getToTechnicianId() {
    return toTechnicianId;
  }

  public void setToTechnicianId(@javax.annotation.Nullable UUID toTechnicianId) {
    this.toTechnicianId = toTechnicianId;
  }


  public JobRequestAbsenceAlternative totalScore(@javax.annotation.Nullable BigDecimal totalScore) {
    this.totalScore = totalScore;
    return this;
  }

  /**
   * Engine ranking score (0..1) — comparable within one option&#39;s candidate list only.
   * @return totalScore
   */
  @javax.annotation.Nullable
  public BigDecimal getTotalScore() {
    return totalScore;
  }

  public void setTotalScore(@javax.annotation.Nullable BigDecimal totalScore) {
    this.totalScore = totalScore;
  }


  public JobRequestAbsenceAlternative windowMoved(@javax.annotation.Nullable Boolean windowMoved) {
    this.windowMoved = windowMoved;
    return this;
  }

  /**
   * Convenience mirror of cost.window_moved.
   * @return windowMoved
   */
  @javax.annotation.Nullable
  public Boolean getWindowMoved() {
    return windowMoved;
  }

  public void setWindowMoved(@javax.annotation.Nullable Boolean windowMoved) {
    this.windowMoved = windowMoved;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobRequestAbsenceAlternative jobRequestAbsenceAlternative = (JobRequestAbsenceAlternative) o;
    return Objects.equals(this.cost, jobRequestAbsenceAlternative.cost) &&
        Objects.equals(this.desiredSkills, jobRequestAbsenceAlternative.desiredSkills) &&
        Objects.equals(this.endAt, jobRequestAbsenceAlternative.endAt) &&
        Objects.equals(this.feasibleCount, jobRequestAbsenceAlternative.feasibleCount) &&
        Objects.equals(this.kind, jobRequestAbsenceAlternative.kind) &&
        Objects.equals(this.matchedSkills, jobRequestAbsenceAlternative.matchedSkills) &&
        Objects.equals(this.startAt, jobRequestAbsenceAlternative.startAt) &&
        Objects.equals(this.statusVersion, jobRequestAbsenceAlternative.statusVersion) &&
        Objects.equals(this.toName, jobRequestAbsenceAlternative.toName) &&
        Objects.equals(this.toTechnicianId, jobRequestAbsenceAlternative.toTechnicianId) &&
        Objects.equals(this.totalScore, jobRequestAbsenceAlternative.totalScore) &&
        Objects.equals(this.windowMoved, jobRequestAbsenceAlternative.windowMoved);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cost, desiredSkills, endAt, feasibleCount, kind, matchedSkills, startAt, statusVersion, toName, toTechnicianId, totalScore, windowMoved);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobRequestAbsenceAlternative {\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    desiredSkills: ").append(toIndentedString(desiredSkills)).append("\n");
    sb.append("    endAt: ").append(toIndentedString(endAt)).append("\n");
    sb.append("    feasibleCount: ").append(toIndentedString(feasibleCount)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    matchedSkills: ").append(toIndentedString(matchedSkills)).append("\n");
    sb.append("    startAt: ").append(toIndentedString(startAt)).append("\n");
    sb.append("    statusVersion: ").append(toIndentedString(statusVersion)).append("\n");
    sb.append("    toName: ").append(toIndentedString(toName)).append("\n");
    sb.append("    toTechnicianId: ").append(toIndentedString(toTechnicianId)).append("\n");
    sb.append("    totalScore: ").append(toIndentedString(totalScore)).append("\n");
    sb.append("    windowMoved: ").append(toIndentedString(windowMoved)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cost");
    openapiFields.add("desired_skills");
    openapiFields.add("end_at");
    openapiFields.add("feasible_count");
    openapiFields.add("kind");
    openapiFields.add("matched_skills");
    openapiFields.add("start_at");
    openapiFields.add("status_version");
    openapiFields.add("to_name");
    openapiFields.add("to_technician_id");
    openapiFields.add("total_score");
    openapiFields.add("window_moved");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobRequestAbsenceAlternative
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobRequestAbsenceAlternative.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobRequestAbsenceAlternative is not found in the empty JSON string", JobRequestAbsenceAlternative.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobRequestAbsenceAlternative.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JobRequestAbsenceAlternative` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `cost`
      if (jsonObj.get("cost") != null && !jsonObj.get("cost").isJsonNull()) {
        JobRequestAbsenceAlternativeCost.validateJsonElement(jsonObj.get("cost"));
      }
      if ((jsonObj.get("kind") != null && !jsonObj.get("kind").isJsonNull()) && !jsonObj.get("kind").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `kind` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kind").toString()));
      }
      // validate the optional field `kind`
      if (jsonObj.get("kind") != null && !jsonObj.get("kind").isJsonNull()) {
        KindEnum.validateJsonElement(jsonObj.get("kind"));
      }
      if ((jsonObj.get("to_name") != null && !jsonObj.get("to_name").isJsonNull()) && !jsonObj.get("to_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `to_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("to_name").toString()));
      }
      if ((jsonObj.get("to_technician_id") != null && !jsonObj.get("to_technician_id").isJsonNull()) && !jsonObj.get("to_technician_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `to_technician_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("to_technician_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobRequestAbsenceAlternative.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobRequestAbsenceAlternative' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobRequestAbsenceAlternative> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobRequestAbsenceAlternative.class));

       return (TypeAdapter<T>) new TypeAdapter<JobRequestAbsenceAlternative>() {
           @Override
           public void write(JsonWriter out, JobRequestAbsenceAlternative value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobRequestAbsenceAlternative read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobRequestAbsenceAlternative given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobRequestAbsenceAlternative
   * @throws IOException if the JSON string is invalid with respect to JobRequestAbsenceAlternative
   */
  public static JobRequestAbsenceAlternative fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobRequestAbsenceAlternative.class);
  }

  /**
   * Convert an instance of JobRequestAbsenceAlternative to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

