/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * JobRequestTimeSegmentsWorker
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class JobRequestTimeSegmentsWorker {
  public static final String SERIALIZED_NAME_DISTANCE_KM = "distance_km";
  @SerializedName(SERIALIZED_NAME_DISTANCE_KM)
  @javax.annotation.Nullable
  private BigDecimal distanceKm;

  public static final String SERIALIZED_NAME_DISTANCE_SCORE = "distance_score";
  @SerializedName(SERIALIZED_NAME_DISTANCE_SCORE)
  @javax.annotation.Nullable
  private BigDecimal distanceScore;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private UUID id;

  public static final String SERIALIZED_NAME_JOB_DURATION_TODAY_MINUTES = "job_duration_today_minutes";
  @SerializedName(SERIALIZED_NAME_JOB_DURATION_TODAY_MINUTES)
  @javax.annotation.Nullable
  private Integer jobDurationTodayMinutes;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_TOTAL_SCORE = "total_score";
  @SerializedName(SERIALIZED_NAME_TOTAL_SCORE)
  @javax.annotation.Nullable
  private BigDecimal totalScore;

  public static final String SERIALIZED_NAME_TRAVEL_TIME_SCORE = "travel_time_score";
  @SerializedName(SERIALIZED_NAME_TRAVEL_TIME_SCORE)
  @javax.annotation.Nullable
  private BigDecimal travelTimeScore;

  public static final String SERIALIZED_NAME_WRENCH_TIME_SCORE = "wrench_time_score";
  @SerializedName(SERIALIZED_NAME_WRENCH_TIME_SCORE)
  @javax.annotation.Nullable
  private BigDecimal wrenchTimeScore;

  public JobRequestTimeSegmentsWorker() {
  }

  public JobRequestTimeSegmentsWorker distanceKm(@javax.annotation.Nullable BigDecimal distanceKm) {
    this.distanceKm = distanceKm;
    return this;
  }

  /**
   * Estimated one-way distance from the technician&#39;s start location to the job site, in km (routing-provider estimate, straight-line fallback). 0 when unknown or on the pre-quote fallback path.
   * @return distanceKm
   */
  @javax.annotation.Nullable
  public BigDecimal getDistanceKm() {
    return distanceKm;
  }

  public void setDistanceKm(@javax.annotation.Nullable BigDecimal distanceKm) {
    this.distanceKm = distanceKm;
  }


  public JobRequestTimeSegmentsWorker distanceScore(@javax.annotation.Nullable BigDecimal distanceScore) {
    this.distanceScore = distanceScore;
    return this;
  }

  /**
   * Distance sub-score (0-100; closer to the job &#x3D; higher).
   * @return distanceScore
   */
  @javax.annotation.Nullable
  public BigDecimal getDistanceScore() {
    return distanceScore;
  }

  public void setDistanceScore(@javax.annotation.Nullable BigDecimal distanceScore) {
    this.distanceScore = distanceScore;
  }


  public JobRequestTimeSegmentsWorker email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Technician&#39;s email; empty when not on file.
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public JobRequestTimeSegmentsWorker id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Technician UUID.
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public JobRequestTimeSegmentsWorker jobDurationTodayMinutes(@javax.annotation.Nullable Integer jobDurationTodayMinutes) {
    this.jobDurationTodayMinutes = jobDurationTodayMinutes;
    return this;
  }

  /**
   * Minutes of job work already booked on this technician&#39;s schedule around the offered window (feeds the wrench-time score; lower &#x3D; more open capacity).
   * @return jobDurationTodayMinutes
   */
  @javax.annotation.Nullable
  public Integer getJobDurationTodayMinutes() {
    return jobDurationTodayMinutes;
  }

  public void setJobDurationTodayMinutes(@javax.annotation.Nullable Integer jobDurationTodayMinutes) {
    this.jobDurationTodayMinutes = jobDurationTodayMinutes;
  }


  public JobRequestTimeSegmentsWorker name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Technician&#39;s full display name.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public JobRequestTimeSegmentsWorker totalScore(@javax.annotation.Nullable BigDecimal totalScore) {
    this.totalScore = totalScore;
    return this;
  }

  /**
   * Overall ranking score (0-100): weighted blend of the distance, travel-time, wrench-time and skill sub-scores; workers are listed best-first. Placeholder values on the pre-quote fallback path.
   * @return totalScore
   */
  @javax.annotation.Nullable
  public BigDecimal getTotalScore() {
    return totalScore;
  }

  public void setTotalScore(@javax.annotation.Nullable BigDecimal totalScore) {
    this.totalScore = totalScore;
  }


  public JobRequestTimeSegmentsWorker travelTimeScore(@javax.annotation.Nullable BigDecimal travelTimeScore) {
    this.travelTimeScore = travelTimeScore;
    return this;
  }

  /**
   * Travel-time sub-score (0-100; shorter commute &#x3D; higher).
   * @return travelTimeScore
   */
  @javax.annotation.Nullable
  public BigDecimal getTravelTimeScore() {
    return travelTimeScore;
  }

  public void setTravelTimeScore(@javax.annotation.Nullable BigDecimal travelTimeScore) {
    this.travelTimeScore = travelTimeScore;
  }


  public JobRequestTimeSegmentsWorker wrenchTimeScore(@javax.annotation.Nullable BigDecimal wrenchTimeScore) {
    this.wrenchTimeScore = wrenchTimeScore;
    return this;
  }

  /**
   * Wrench-time sub-score (0-100; more open capacity vs the daily booked-work goal &#x3D; higher).
   * @return wrenchTimeScore
   */
  @javax.annotation.Nullable
  public BigDecimal getWrenchTimeScore() {
    return wrenchTimeScore;
  }

  public void setWrenchTimeScore(@javax.annotation.Nullable BigDecimal wrenchTimeScore) {
    this.wrenchTimeScore = wrenchTimeScore;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobRequestTimeSegmentsWorker jobRequestTimeSegmentsWorker = (JobRequestTimeSegmentsWorker) o;
    return Objects.equals(this.distanceKm, jobRequestTimeSegmentsWorker.distanceKm) &&
        Objects.equals(this.distanceScore, jobRequestTimeSegmentsWorker.distanceScore) &&
        Objects.equals(this.email, jobRequestTimeSegmentsWorker.email) &&
        Objects.equals(this.id, jobRequestTimeSegmentsWorker.id) &&
        Objects.equals(this.jobDurationTodayMinutes, jobRequestTimeSegmentsWorker.jobDurationTodayMinutes) &&
        Objects.equals(this.name, jobRequestTimeSegmentsWorker.name) &&
        Objects.equals(this.totalScore, jobRequestTimeSegmentsWorker.totalScore) &&
        Objects.equals(this.travelTimeScore, jobRequestTimeSegmentsWorker.travelTimeScore) &&
        Objects.equals(this.wrenchTimeScore, jobRequestTimeSegmentsWorker.wrenchTimeScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(distanceKm, distanceScore, email, id, jobDurationTodayMinutes, name, totalScore, travelTimeScore, wrenchTimeScore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobRequestTimeSegmentsWorker {\n");
    sb.append("    distanceKm: ").append(toIndentedString(distanceKm)).append("\n");
    sb.append("    distanceScore: ").append(toIndentedString(distanceScore)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jobDurationTodayMinutes: ").append(toIndentedString(jobDurationTodayMinutes)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    totalScore: ").append(toIndentedString(totalScore)).append("\n");
    sb.append("    travelTimeScore: ").append(toIndentedString(travelTimeScore)).append("\n");
    sb.append("    wrenchTimeScore: ").append(toIndentedString(wrenchTimeScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("distance_km");
    openapiFields.add("distance_score");
    openapiFields.add("email");
    openapiFields.add("id");
    openapiFields.add("job_duration_today_minutes");
    openapiFields.add("name");
    openapiFields.add("total_score");
    openapiFields.add("travel_time_score");
    openapiFields.add("wrench_time_score");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobRequestTimeSegmentsWorker
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobRequestTimeSegmentsWorker.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobRequestTimeSegmentsWorker is not found in the empty JSON string", JobRequestTimeSegmentsWorker.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobRequestTimeSegmentsWorker.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JobRequestTimeSegmentsWorker` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobRequestTimeSegmentsWorker.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobRequestTimeSegmentsWorker' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobRequestTimeSegmentsWorker> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobRequestTimeSegmentsWorker.class));

       return (TypeAdapter<T>) new TypeAdapter<JobRequestTimeSegmentsWorker>() {
           @Override
           public void write(JsonWriter out, JobRequestTimeSegmentsWorker value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobRequestTimeSegmentsWorker read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobRequestTimeSegmentsWorker given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobRequestTimeSegmentsWorker
   * @throws IOException if the JSON string is invalid with respect to JobRequestTimeSegmentsWorker
   */
  public static JobRequestTimeSegmentsWorker fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobRequestTimeSegmentsWorker.class);
  }

  /**
   * Convert an instance of JobRequestTimeSegmentsWorker to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

