/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * JobRequestAbsenceAlternativeCost
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class JobRequestAbsenceAlternativeCost {
  public static final String SERIALIZED_NAME_CUSTOMER_RENOTIFIED = "customer_renotified";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_RENOTIFIED)
  @javax.annotation.Nullable
  private Boolean customerRenotified;

  public static final String SERIALIZED_NAME_DAY_OFFSET = "day_offset";
  @SerializedName(SERIALIZED_NAME_DAY_OFFSET)
  @javax.annotation.Nullable
  private Integer dayOffset;

  public static final String SERIALIZED_NAME_DISTANCE_KM = "distance_km";
  @SerializedName(SERIALIZED_NAME_DISTANCE_KM)
  @javax.annotation.Nullable
  private BigDecimal distanceKm;

  public static final String SERIALIZED_NAME_OUTSIDE_SERVICE_AREA = "outside_service_area";
  @SerializedName(SERIALIZED_NAME_OUTSIDE_SERVICE_AREA)
  @javax.annotation.Nullable
  private Boolean outsideServiceArea;

  public static final String SERIALIZED_NAME_SLA_BREACHED = "sla_breached";
  @SerializedName(SERIALIZED_NAME_SLA_BREACHED)
  @javax.annotation.Nullable
  private Boolean slaBreached;

  public static final String SERIALIZED_NAME_TRAVEL_MINUTES = "travel_minutes";
  @SerializedName(SERIALIZED_NAME_TRAVEL_MINUTES)
  @javax.annotation.Nullable
  private Integer travelMinutes;

  public static final String SERIALIZED_NAME_WINDOW_MOVED = "window_moved";
  @SerializedName(SERIALIZED_NAME_WINDOW_MOVED)
  @javax.annotation.Nullable
  private Boolean windowMoved;

  public JobRequestAbsenceAlternativeCost() {
  }

  public JobRequestAbsenceAlternativeCost customerRenotified(@javax.annotation.Nullable Boolean customerRenotified) {
    this.customerRenotified = customerRenotified;
    return this;
  }

  /**
   * The customer is told a NEW appointment time (job_rescheduled), not only a new technician name.
   * @return customerRenotified
   */
  @javax.annotation.Nullable
  public Boolean getCustomerRenotified() {
    return customerRenotified;
  }

  public void setCustomerRenotified(@javax.annotation.Nullable Boolean customerRenotified) {
    this.customerRenotified = customerRenotified;
  }


  public JobRequestAbsenceAlternativeCost dayOffset(@javax.annotation.Nullable Integer dayOffset) {
    this.dayOffset = dayOffset;
    return this;
  }

  /**
   * Calendar days between the original and the new window&#39;s business-local dates (0 &#x3D; same day / reassign).
   * @return dayOffset
   */
  @javax.annotation.Nullable
  public Integer getDayOffset() {
    return dayOffset;
  }

  public void setDayOffset(@javax.annotation.Nullable Integer dayOffset) {
    this.dayOffset = dayOffset;
  }


  public JobRequestAbsenceAlternativeCost distanceKm(@javax.annotation.Nullable BigDecimal distanceKm) {
    this.distanceKm = distanceKm;
    return this;
  }

  /**
   * The technician&#39;s own driving distance to the site in km. ABSENT when the engine had no route — never render \&quot;0 km\&quot;.
   * @return distanceKm
   */
  @javax.annotation.Nullable
  public BigDecimal getDistanceKm() {
    return distanceKm;
  }

  public void setDistanceKm(@javax.annotation.Nullable BigDecimal distanceKm) {
    this.distanceKm = distanceKm;
  }


  public JobRequestAbsenceAlternativeCost outsideServiceArea(@javax.annotation.Nullable Boolean outsideServiceArea) {
    this.outsideServiceArea = outsideServiceArea;
    return this;
  }

  /**
   * The technician is not assigned to any service area covering the job (sent out of zone).
   * @return outsideServiceArea
   */
  @javax.annotation.Nullable
  public Boolean getOutsideServiceArea() {
    return outsideServiceArea;
  }

  public void setOutsideServiceArea(@javax.annotation.Nullable Boolean outsideServiceArea) {
    this.outsideServiceArea = outsideServiceArea;
  }


  public JobRequestAbsenceAlternativeCost slaBreached(@javax.annotation.Nullable Boolean slaBreached) {
    this.slaBreached = slaBreached;
    return this;
  }

  /**
   * The job carries an SLA deadline and the new window ends after it.
   * @return slaBreached
   */
  @javax.annotation.Nullable
  public Boolean getSlaBreached() {
    return slaBreached;
  }

  public void setSlaBreached(@javax.annotation.Nullable Boolean slaBreached) {
    this.slaBreached = slaBreached;
  }


  public JobRequestAbsenceAlternativeCost travelMinutes(@javax.annotation.Nullable Integer travelMinutes) {
    this.travelMinutes = travelMinutes;
    return this;
  }

  /**
   * The technician&#39;s one-way commute estimate in minutes (rounded up). Absent when unknown.
   * @return travelMinutes
   */
  @javax.annotation.Nullable
  public Integer getTravelMinutes() {
    return travelMinutes;
  }

  public void setTravelMinutes(@javax.annotation.Nullable Integer travelMinutes) {
    this.travelMinutes = travelMinutes;
  }


  public JobRequestAbsenceAlternativeCost windowMoved(@javax.annotation.Nullable Boolean windowMoved) {
    this.windowMoved = windowMoved;
    return this;
  }

  /**
   * The customer&#39;s appointment changes (reschedule kinds).
   * @return windowMoved
   */
  @javax.annotation.Nullable
  public Boolean getWindowMoved() {
    return windowMoved;
  }

  public void setWindowMoved(@javax.annotation.Nullable Boolean windowMoved) {
    this.windowMoved = windowMoved;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobRequestAbsenceAlternativeCost jobRequestAbsenceAlternativeCost = (JobRequestAbsenceAlternativeCost) o;
    return Objects.equals(this.customerRenotified, jobRequestAbsenceAlternativeCost.customerRenotified) &&
        Objects.equals(this.dayOffset, jobRequestAbsenceAlternativeCost.dayOffset) &&
        Objects.equals(this.distanceKm, jobRequestAbsenceAlternativeCost.distanceKm) &&
        Objects.equals(this.outsideServiceArea, jobRequestAbsenceAlternativeCost.outsideServiceArea) &&
        Objects.equals(this.slaBreached, jobRequestAbsenceAlternativeCost.slaBreached) &&
        Objects.equals(this.travelMinutes, jobRequestAbsenceAlternativeCost.travelMinutes) &&
        Objects.equals(this.windowMoved, jobRequestAbsenceAlternativeCost.windowMoved);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerRenotified, dayOffset, distanceKm, outsideServiceArea, slaBreached, travelMinutes, windowMoved);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobRequestAbsenceAlternativeCost {\n");
    sb.append("    customerRenotified: ").append(toIndentedString(customerRenotified)).append("\n");
    sb.append("    dayOffset: ").append(toIndentedString(dayOffset)).append("\n");
    sb.append("    distanceKm: ").append(toIndentedString(distanceKm)).append("\n");
    sb.append("    outsideServiceArea: ").append(toIndentedString(outsideServiceArea)).append("\n");
    sb.append("    slaBreached: ").append(toIndentedString(slaBreached)).append("\n");
    sb.append("    travelMinutes: ").append(toIndentedString(travelMinutes)).append("\n");
    sb.append("    windowMoved: ").append(toIndentedString(windowMoved)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("customer_renotified");
    openapiFields.add("day_offset");
    openapiFields.add("distance_km");
    openapiFields.add("outside_service_area");
    openapiFields.add("sla_breached");
    openapiFields.add("travel_minutes");
    openapiFields.add("window_moved");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobRequestAbsenceAlternativeCost
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobRequestAbsenceAlternativeCost.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobRequestAbsenceAlternativeCost is not found in the empty JSON string", JobRequestAbsenceAlternativeCost.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobRequestAbsenceAlternativeCost.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JobRequestAbsenceAlternativeCost` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobRequestAbsenceAlternativeCost.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobRequestAbsenceAlternativeCost' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobRequestAbsenceAlternativeCost> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobRequestAbsenceAlternativeCost.class));

       return (TypeAdapter<T>) new TypeAdapter<JobRequestAbsenceAlternativeCost>() {
           @Override
           public void write(JsonWriter out, JobRequestAbsenceAlternativeCost value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobRequestAbsenceAlternativeCost read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobRequestAbsenceAlternativeCost given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobRequestAbsenceAlternativeCost
   * @throws IOException if the JSON string is invalid with respect to JobRequestAbsenceAlternativeCost
   */
  public static JobRequestAbsenceAlternativeCost fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobRequestAbsenceAlternativeCost.class);
  }

  /**
   * Convert an instance of JobRequestAbsenceAlternativeCost to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

