/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * JobRequestRescheduleMove
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class JobRequestRescheduleMove {
  public static final String SERIALIZED_NAME_CUSTOMER_NAME = "customer_name";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_NAME)
  @javax.annotation.Nullable
  private String customerName;

  public static final String SERIALIZED_NAME_FROM_END = "from_end";
  @SerializedName(SERIALIZED_NAME_FROM_END)
  @javax.annotation.Nullable
  private OffsetDateTime fromEnd;

  public static final String SERIALIZED_NAME_FROM_START = "from_start";
  @SerializedName(SERIALIZED_NAME_FROM_START)
  @javax.annotation.Nullable
  private OffsetDateTime fromStart;

  public static final String SERIALIZED_NAME_JOB_ID = "job_id";
  @SerializedName(SERIALIZED_NAME_JOB_ID)
  @javax.annotation.Nullable
  private UUID jobId;

  /**
   * Priority of the displaced job (p0..p3) — what the coordinator is pushing.
   */
  @JsonAdapter(PriorityEnum.Adapter.class)
  public enum PriorityEnum {
    P0("p0"),
    
    P1("p1"),
    
    P2("p2"),
    
    P3("p3");

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PriorityEnum fromValue(String value) {
      for (PriorityEnum b : PriorityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PriorityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PriorityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PriorityEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PriorityEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      PriorityEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  @javax.annotation.Nullable
  private PriorityEnum priority;

  public static final String SERIALIZED_NAME_SHORT_CODE = "short_code";
  @SerializedName(SERIALIZED_NAME_SHORT_CODE)
  @javax.annotation.Nullable
  private String shortCode;

  public static final String SERIALIZED_NAME_TO_END = "to_end";
  @SerializedName(SERIALIZED_NAME_TO_END)
  @javax.annotation.Nullable
  private OffsetDateTime toEnd;

  public static final String SERIALIZED_NAME_TO_START = "to_start";
  @SerializedName(SERIALIZED_NAME_TO_START)
  @javax.annotation.Nullable
  private OffsetDateTime toStart;

  public JobRequestRescheduleMove() {
  }

  public JobRequestRescheduleMove customerName(@javax.annotation.Nullable String customerName) {
    this.customerName = customerName;
    return this;
  }

  /**
   * Name of the displaced job&#39;s customer.
   * @return customerName
   */
  @javax.annotation.Nullable
  public String getCustomerName() {
    return customerName;
  }

  public void setCustomerName(@javax.annotation.Nullable String customerName) {
    this.customerName = customerName;
  }


  public JobRequestRescheduleMove fromEnd(@javax.annotation.Nullable OffsetDateTime fromEnd) {
    this.fromEnd = fromEnd;
    return this;
  }

  /**
   * Current window end (UTC).
   * @return fromEnd
   */
  @javax.annotation.Nullable
  public OffsetDateTime getFromEnd() {
    return fromEnd;
  }

  public void setFromEnd(@javax.annotation.Nullable OffsetDateTime fromEnd) {
    this.fromEnd = fromEnd;
  }


  public JobRequestRescheduleMove fromStart(@javax.annotation.Nullable OffsetDateTime fromStart) {
    this.fromStart = fromStart;
    return this;
  }

  /**
   * Current window start (UTC) — where the job sits today.
   * @return fromStart
   */
  @javax.annotation.Nullable
  public OffsetDateTime getFromStart() {
    return fromStart;
  }

  public void setFromStart(@javax.annotation.Nullable OffsetDateTime fromStart) {
    this.fromStart = fromStart;
  }


  public JobRequestRescheduleMove jobId(@javax.annotation.Nullable UUID jobId) {
    this.jobId = jobId;
    return this;
  }

  /**
   * UUID of the displaced job.
   * @return jobId
   */
  @javax.annotation.Nullable
  public UUID getJobId() {
    return jobId;
  }

  public void setJobId(@javax.annotation.Nullable UUID jobId) {
    this.jobId = jobId;
  }


  public JobRequestRescheduleMove priority(@javax.annotation.Nullable PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Priority of the displaced job (p0..p3) — what the coordinator is pushing.
   * @return priority
   */
  @javax.annotation.Nullable
  public PriorityEnum getPriority() {
    return priority;
  }

  public void setPriority(@javax.annotation.Nullable PriorityEnum priority) {
    this.priority = priority;
  }


  public JobRequestRescheduleMove shortCode(@javax.annotation.Nullable String shortCode) {
    this.shortCode = shortCode;
    return this;
  }

  /**
   * Human-friendly short code of the displaced job.
   * @return shortCode
   */
  @javax.annotation.Nullable
  public String getShortCode() {
    return shortCode;
  }

  public void setShortCode(@javax.annotation.Nullable String shortCode) {
    this.shortCode = shortCode;
  }


  public JobRequestRescheduleMove toEnd(@javax.annotation.Nullable OffsetDateTime toEnd) {
    this.toEnd = toEnd;
    return this;
  }

  /**
   * Proposed window end (UTC).
   * @return toEnd
   */
  @javax.annotation.Nullable
  public OffsetDateTime getToEnd() {
    return toEnd;
  }

  public void setToEnd(@javax.annotation.Nullable OffsetDateTime toEnd) {
    this.toEnd = toEnd;
  }


  public JobRequestRescheduleMove toStart(@javax.annotation.Nullable OffsetDateTime toStart) {
    this.toStart = toStart;
    return this;
  }

  /**
   * Proposed window start (UTC) — where the job lands after the cascade.
   * @return toStart
   */
  @javax.annotation.Nullable
  public OffsetDateTime getToStart() {
    return toStart;
  }

  public void setToStart(@javax.annotation.Nullable OffsetDateTime toStart) {
    this.toStart = toStart;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobRequestRescheduleMove jobRequestRescheduleMove = (JobRequestRescheduleMove) o;
    return Objects.equals(this.customerName, jobRequestRescheduleMove.customerName) &&
        Objects.equals(this.fromEnd, jobRequestRescheduleMove.fromEnd) &&
        Objects.equals(this.fromStart, jobRequestRescheduleMove.fromStart) &&
        Objects.equals(this.jobId, jobRequestRescheduleMove.jobId) &&
        Objects.equals(this.priority, jobRequestRescheduleMove.priority) &&
        Objects.equals(this.shortCode, jobRequestRescheduleMove.shortCode) &&
        Objects.equals(this.toEnd, jobRequestRescheduleMove.toEnd) &&
        Objects.equals(this.toStart, jobRequestRescheduleMove.toStart);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerName, fromEnd, fromStart, jobId, priority, shortCode, toEnd, toStart);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobRequestRescheduleMove {\n");
    sb.append("    customerName: ").append(toIndentedString(customerName)).append("\n");
    sb.append("    fromEnd: ").append(toIndentedString(fromEnd)).append("\n");
    sb.append("    fromStart: ").append(toIndentedString(fromStart)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    shortCode: ").append(toIndentedString(shortCode)).append("\n");
    sb.append("    toEnd: ").append(toIndentedString(toEnd)).append("\n");
    sb.append("    toStart: ").append(toIndentedString(toStart)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("customer_name");
    openapiFields.add("from_end");
    openapiFields.add("from_start");
    openapiFields.add("job_id");
    openapiFields.add("priority");
    openapiFields.add("short_code");
    openapiFields.add("to_end");
    openapiFields.add("to_start");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobRequestRescheduleMove
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobRequestRescheduleMove.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobRequestRescheduleMove is not found in the empty JSON string", JobRequestRescheduleMove.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobRequestRescheduleMove.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JobRequestRescheduleMove` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("customer_name") != null && !jsonObj.get("customer_name").isJsonNull()) && !jsonObj.get("customer_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customer_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customer_name").toString()));
      }
      if ((jsonObj.get("job_id") != null && !jsonObj.get("job_id").isJsonNull()) && !jsonObj.get("job_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `job_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("job_id").toString()));
      }
      if ((jsonObj.get("priority") != null && !jsonObj.get("priority").isJsonNull()) && !jsonObj.get("priority").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `priority` to be a primitive type in the JSON string but got `%s`", jsonObj.get("priority").toString()));
      }
      // validate the optional field `priority`
      if (jsonObj.get("priority") != null && !jsonObj.get("priority").isJsonNull()) {
        PriorityEnum.validateJsonElement(jsonObj.get("priority"));
      }
      if ((jsonObj.get("short_code") != null && !jsonObj.get("short_code").isJsonNull()) && !jsonObj.get("short_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `short_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("short_code").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobRequestRescheduleMove.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobRequestRescheduleMove' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobRequestRescheduleMove> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobRequestRescheduleMove.class));

       return (TypeAdapter<T>) new TypeAdapter<JobRequestRescheduleMove>() {
           @Override
           public void write(JsonWriter out, JobRequestRescheduleMove value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobRequestRescheduleMove read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobRequestRescheduleMove given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobRequestRescheduleMove
   * @throws IOException if the JSON string is invalid with respect to JobRequestRescheduleMove
   */
  public static JobRequestRescheduleMove fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobRequestRescheduleMove.class);
  }

  /**
   * Convert an instance of JobRequestRescheduleMove to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

