/*
 * CrispHive Developer API
 * Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * JobRequestRatingSummary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class JobRequestRatingSummary {
  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  @javax.annotation.Nullable
  private String comment;

  public static final String SERIALIZED_NAME_IS_RATED = "is_rated";
  @SerializedName(SERIALIZED_NAME_IS_RATED)
  @javax.annotation.Nullable
  private Boolean isRated;

  public static final String SERIALIZED_NAME_RATED_AT = "rated_at";
  @SerializedName(SERIALIZED_NAME_RATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime ratedAt;

  public static final String SERIALIZED_NAME_SCORE = "score";
  @SerializedName(SERIALIZED_NAME_SCORE)
  @javax.annotation.Nullable
  private Integer score;

  public JobRequestRatingSummary() {
  }

  public JobRequestRatingSummary comment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Optional free-text rating comment; null if none.
   * @return comment
   */
  @javax.annotation.Nullable
  public String getComment() {
    return comment;
  }

  public void setComment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
  }


  public JobRequestRatingSummary isRated(@javax.annotation.Nullable Boolean isRated) {
    this.isRated = isRated;
    return this;
  }

  /**
   * Whether the customer has rated the job.
   * @return isRated
   */
  @javax.annotation.Nullable
  public Boolean getIsRated() {
    return isRated;
  }

  public void setIsRated(@javax.annotation.Nullable Boolean isRated) {
    this.isRated = isRated;
  }


  public JobRequestRatingSummary ratedAt(@javax.annotation.Nullable OffsetDateTime ratedAt) {
    this.ratedAt = ratedAt;
    return this;
  }

  /**
   * When the job was rated (UTC); null if not rated.
   * @return ratedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getRatedAt() {
    return ratedAt;
  }

  public void setRatedAt(@javax.annotation.Nullable OffsetDateTime ratedAt) {
    this.ratedAt = ratedAt;
  }


  public JobRequestRatingSummary score(@javax.annotation.Nullable Integer score) {
    this.score = score;
    return this;
  }

  /**
   * Rating score (1–5); null if not rated.
   * @return score
   */
  @javax.annotation.Nullable
  public Integer getScore() {
    return score;
  }

  public void setScore(@javax.annotation.Nullable Integer score) {
    this.score = score;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobRequestRatingSummary jobRequestRatingSummary = (JobRequestRatingSummary) o;
    return Objects.equals(this.comment, jobRequestRatingSummary.comment) &&
        Objects.equals(this.isRated, jobRequestRatingSummary.isRated) &&
        Objects.equals(this.ratedAt, jobRequestRatingSummary.ratedAt) &&
        Objects.equals(this.score, jobRequestRatingSummary.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comment, isRated, ratedAt, score);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobRequestRatingSummary {\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    isRated: ").append(toIndentedString(isRated)).append("\n");
    sb.append("    ratedAt: ").append(toIndentedString(ratedAt)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("comment");
    openapiFields.add("is_rated");
    openapiFields.add("rated_at");
    openapiFields.add("score");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobRequestRatingSummary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobRequestRatingSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobRequestRatingSummary is not found in the empty JSON string", JobRequestRatingSummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobRequestRatingSummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JobRequestRatingSummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonNull()) && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobRequestRatingSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobRequestRatingSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobRequestRatingSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobRequestRatingSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<JobRequestRatingSummary>() {
           @Override
           public void write(JsonWriter out, JobRequestRatingSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobRequestRatingSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobRequestRatingSummary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobRequestRatingSummary
   * @throws IOException if the JSON string is invalid with respect to JobRequestRatingSummary
   */
  public static JobRequestRatingSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobRequestRatingSummary.class);
  }

  /**
   * Convert an instance of JobRequestRatingSummary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

