/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * JobRequestCreateResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class JobRequestCreateResponse {
  public static final String SERIALIZED_NAME_CUSTOMER_URL = "customer_url";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_URL)
  @javax.annotation.Nullable
  private String customerUrl;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private UUID id;

  public static final String SERIALIZED_NAME_MAGIC_TOKEN = "magic_token";
  @SerializedName(SERIALIZED_NAME_MAGIC_TOKEN)
  @javax.annotation.Nullable
  private String magicToken;

  public static final String SERIALIZED_NAME_SHORT_CODE = "short_code";
  @SerializedName(SERIALIZED_NAME_SHORT_CODE)
  @javax.annotation.Nullable
  private String shortCode;

  public JobRequestCreateResponse() {
  }

  public JobRequestCreateResponse customerUrl(@javax.annotation.Nullable String customerUrl) {
    this.customerUrl = customerUrl;
    return this;
  }

  /**
   * Ready-to-share customer URL embedding the magic token. Omitted if not issued.
   * @return customerUrl
   */
  @javax.annotation.Nullable
  public String getCustomerUrl() {
    return customerUrl;
  }

  public void setCustomerUrl(@javax.annotation.Nullable String customerUrl) {
    this.customerUrl = customerUrl;
  }


  public JobRequestCreateResponse id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * UUID of the newly created job request.
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public JobRequestCreateResponse magicToken(@javax.annotation.Nullable String magicToken) {
    this.magicToken = magicToken;
    return this;
  }

  /**
   * Customer magic-link JWT granting access to this job&#39;s customer pages. Omitted if not issued.
   * @return magicToken
   */
  @javax.annotation.Nullable
  public String getMagicToken() {
    return magicToken;
  }

  public void setMagicToken(@javax.annotation.Nullable String magicToken) {
    this.magicToken = magicToken;
  }


  public JobRequestCreateResponse shortCode(@javax.annotation.Nullable String shortCode) {
    this.shortCode = shortCode;
    return this;
  }

  /**
   * Human-friendly short code for the job (e.g. for customer reference). Omitted if not assigned.
   * @return shortCode
   */
  @javax.annotation.Nullable
  public String getShortCode() {
    return shortCode;
  }

  public void setShortCode(@javax.annotation.Nullable String shortCode) {
    this.shortCode = shortCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobRequestCreateResponse jobRequestCreateResponse = (JobRequestCreateResponse) o;
    return Objects.equals(this.customerUrl, jobRequestCreateResponse.customerUrl) &&
        Objects.equals(this.id, jobRequestCreateResponse.id) &&
        Objects.equals(this.magicToken, jobRequestCreateResponse.magicToken) &&
        Objects.equals(this.shortCode, jobRequestCreateResponse.shortCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerUrl, id, magicToken, shortCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobRequestCreateResponse {\n");
    sb.append("    customerUrl: ").append(toIndentedString(customerUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    magicToken: ").append(toIndentedString(magicToken)).append("\n");
    sb.append("    shortCode: ").append(toIndentedString(shortCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("customer_url");
    openapiFields.add("id");
    openapiFields.add("magic_token");
    openapiFields.add("short_code");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobRequestCreateResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobRequestCreateResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobRequestCreateResponse is not found in the empty JSON string", JobRequestCreateResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobRequestCreateResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JobRequestCreateResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("customer_url") != null && !jsonObj.get("customer_url").isJsonNull()) && !jsonObj.get("customer_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customer_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customer_url").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("magic_token") != null && !jsonObj.get("magic_token").isJsonNull()) && !jsonObj.get("magic_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `magic_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("magic_token").toString()));
      }
      if ((jsonObj.get("short_code") != null && !jsonObj.get("short_code").isJsonNull()) && !jsonObj.get("short_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `short_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("short_code").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobRequestCreateResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobRequestCreateResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobRequestCreateResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobRequestCreateResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<JobRequestCreateResponse>() {
           @Override
           public void write(JsonWriter out, JobRequestCreateResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobRequestCreateResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobRequestCreateResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobRequestCreateResponse
   * @throws IOException if the JSON string is invalid with respect to JobRequestCreateResponse
   */
  public static JobRequestCreateResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobRequestCreateResponse.class);
  }

  /**
   * Convert an instance of JobRequestCreateResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

