/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * JobTypeUpdateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class JobTypeUpdateRequest {
  public static final String SERIALIZED_NAME_DEFAULT_DEMOBILIZATION_MINUTES = "default_demobilization_minutes";
  @SerializedName(SERIALIZED_NAME_DEFAULT_DEMOBILIZATION_MINUTES)
  @javax.annotation.Nullable
  private Integer defaultDemobilizationMinutes;

  public static final String SERIALIZED_NAME_DEFAULT_DURATION_MINUTES = "default_duration_minutes";
  @SerializedName(SERIALIZED_NAME_DEFAULT_DURATION_MINUTES)
  @javax.annotation.Nullable
  private Integer defaultDurationMinutes;

  public static final String SERIALIZED_NAME_DEFAULT_MOBILIZATION_MINUTES = "default_mobilization_minutes";
  @SerializedName(SERIALIZED_NAME_DEFAULT_MOBILIZATION_MINUTES)
  @javax.annotation.Nullable
  private Integer defaultMobilizationMinutes;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("active"),
    
    INACTIVE("inactive");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public JobTypeUpdateRequest() {
  }

  public JobTypeUpdateRequest defaultDemobilizationMinutes(@javax.annotation.Nullable Integer defaultDemobilizationMinutes) {
    this.defaultDemobilizationMinutes = defaultDemobilizationMinutes;
    return this;
  }

  /**
   * Default demobilization (teardown) minutes, 0–1440; used together with the default duration. Requires a default duration. Omit &#x3D; keep, 0 &#x3D; clear.
   * minimum: 0
   * maximum: 1440
   * @return defaultDemobilizationMinutes
   */
  @javax.annotation.Nullable
  public Integer getDefaultDemobilizationMinutes() {
    return defaultDemobilizationMinutes;
  }

  public void setDefaultDemobilizationMinutes(@javax.annotation.Nullable Integer defaultDemobilizationMinutes) {
    this.defaultDemobilizationMinutes = defaultDemobilizationMinutes;
  }


  public JobTypeUpdateRequest defaultDurationMinutes(@javax.annotation.Nullable Integer defaultDurationMinutes) {
    this.defaultDurationMinutes = defaultDurationMinutes;
    return this;
  }

  /**
   * Default hands-on work duration in minutes for this kind of work (1–20160). A quote that sends no job_duration_minutes uses it, which is what lets an automation or voice agent schedule a job without knowing how long the work takes. Omit &#x3D; keep, 0 &#x3D; clear.
   * minimum: 0
   * maximum: 20160
   * @return defaultDurationMinutes
   */
  @javax.annotation.Nullable
  public Integer getDefaultDurationMinutes() {
    return defaultDurationMinutes;
  }

  public void setDefaultDurationMinutes(@javax.annotation.Nullable Integer defaultDurationMinutes) {
    this.defaultDurationMinutes = defaultDurationMinutes;
  }


  public JobTypeUpdateRequest defaultMobilizationMinutes(@javax.annotation.Nullable Integer defaultMobilizationMinutes) {
    this.defaultMobilizationMinutes = defaultMobilizationMinutes;
    return this;
  }

  /**
   * Default mobilization (setup/travel-prep) minutes, 0–1440; used together with the default duration. Requires a default duration. Omit &#x3D; keep, 0 &#x3D; clear.
   * minimum: 0
   * maximum: 1440
   * @return defaultMobilizationMinutes
   */
  @javax.annotation.Nullable
  public Integer getDefaultMobilizationMinutes() {
    return defaultMobilizationMinutes;
  }

  public void setDefaultMobilizationMinutes(@javax.annotation.Nullable Integer defaultMobilizationMinutes) {
    this.defaultMobilizationMinutes = defaultMobilizationMinutes;
  }


  public JobTypeUpdateRequest name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * nil &#x3D; keep; min&#x3D;1 rejects an explicit \&quot;\&quot;.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public JobTypeUpdateRequest status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobTypeUpdateRequest jobTypeUpdateRequest = (JobTypeUpdateRequest) o;
    return Objects.equals(this.defaultDemobilizationMinutes, jobTypeUpdateRequest.defaultDemobilizationMinutes) &&
        Objects.equals(this.defaultDurationMinutes, jobTypeUpdateRequest.defaultDurationMinutes) &&
        Objects.equals(this.defaultMobilizationMinutes, jobTypeUpdateRequest.defaultMobilizationMinutes) &&
        Objects.equals(this.name, jobTypeUpdateRequest.name) &&
        Objects.equals(this.status, jobTypeUpdateRequest.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultDemobilizationMinutes, defaultDurationMinutes, defaultMobilizationMinutes, name, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobTypeUpdateRequest {\n");
    sb.append("    defaultDemobilizationMinutes: ").append(toIndentedString(defaultDemobilizationMinutes)).append("\n");
    sb.append("    defaultDurationMinutes: ").append(toIndentedString(defaultDurationMinutes)).append("\n");
    sb.append("    defaultMobilizationMinutes: ").append(toIndentedString(defaultMobilizationMinutes)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("default_demobilization_minutes");
    openapiFields.add("default_duration_minutes");
    openapiFields.add("default_mobilization_minutes");
    openapiFields.add("name");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to JobTypeUpdateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!JobTypeUpdateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobTypeUpdateRequest is not found in the empty JSON string", JobTypeUpdateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!JobTypeUpdateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JobTypeUpdateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobTypeUpdateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobTypeUpdateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobTypeUpdateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobTypeUpdateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<JobTypeUpdateRequest>() {
           @Override
           public void write(JsonWriter out, JobTypeUpdateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public JobTypeUpdateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of JobTypeUpdateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of JobTypeUpdateRequest
   * @throws IOException if the JSON string is invalid with respect to JobTypeUpdateRequest
   */
  public static JobTypeUpdateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobTypeUpdateRequest.class);
  }

  /**
   * Convert an instance of JobTypeUpdateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

