/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.crisphive.client.model.TechnicianServiceAreaRef;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * TechnicianServiceAreasResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class TechnicianServiceAreasResponse {
  public static final String SERIALIZED_NAME_SERVICE_AREAS = "service_areas";
  @SerializedName(SERIALIZED_NAME_SERVICE_AREAS)
  @javax.annotation.Nullable
  private List<TechnicianServiceAreaRef> serviceAreas = new ArrayList<>();

  public TechnicianServiceAreasResponse() {
  }

  public TechnicianServiceAreasResponse serviceAreas(@javax.annotation.Nullable List<TechnicianServiceAreaRef> serviceAreas) {
    this.serviceAreas = serviceAreas;
    return this;
  }

  public TechnicianServiceAreasResponse addServiceAreasItem(TechnicianServiceAreaRef serviceAreasItem) {
    if (this.serviceAreas == null) {
      this.serviceAreas = new ArrayList<>();
    }
    this.serviceAreas.add(serviceAreasItem);
    return this;
  }

  /**
   * The service areas now assigned to the technician.
   * @return serviceAreas
   */
  @javax.annotation.Nullable
  public List<TechnicianServiceAreaRef> getServiceAreas() {
    return serviceAreas;
  }

  public void setServiceAreas(@javax.annotation.Nullable List<TechnicianServiceAreaRef> serviceAreas) {
    this.serviceAreas = serviceAreas;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TechnicianServiceAreasResponse technicianServiceAreasResponse = (TechnicianServiceAreasResponse) o;
    return Objects.equals(this.serviceAreas, technicianServiceAreasResponse.serviceAreas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceAreas);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TechnicianServiceAreasResponse {\n");
    sb.append("    serviceAreas: ").append(toIndentedString(serviceAreas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("service_areas");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TechnicianServiceAreasResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TechnicianServiceAreasResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TechnicianServiceAreasResponse is not found in the empty JSON string", TechnicianServiceAreasResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TechnicianServiceAreasResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TechnicianServiceAreasResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("service_areas") != null && !jsonObj.get("service_areas").isJsonNull()) {
        JsonArray jsonArrayserviceAreas = jsonObj.getAsJsonArray("service_areas");
        if (jsonArrayserviceAreas != null) {
          // ensure the json data is an array
          if (!jsonObj.get("service_areas").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `service_areas` to be an array in the JSON string but got `%s`", jsonObj.get("service_areas").toString()));
          }

          // validate the optional field `service_areas` (array)
          for (int i = 0; i < jsonArrayserviceAreas.size(); i++) {
            TechnicianServiceAreaRef.validateJsonElement(jsonArrayserviceAreas.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TechnicianServiceAreasResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TechnicianServiceAreasResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TechnicianServiceAreasResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TechnicianServiceAreasResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<TechnicianServiceAreasResponse>() {
           @Override
           public void write(JsonWriter out, TechnicianServiceAreasResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TechnicianServiceAreasResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TechnicianServiceAreasResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TechnicianServiceAreasResponse
   * @throws IOException if the JSON string is invalid with respect to TechnicianServiceAreasResponse
   */
  public static TechnicianServiceAreasResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TechnicianServiceAreasResponse.class);
  }

  /**
   * Convert an instance of TechnicianServiceAreasResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

