/*
 * CrispHive Developer API
 * Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.crisphive.client.model.Pagination;
import com.crisphive.client.model.Technician;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * TechnicianList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class TechnicianList {
  public static final String SERIALIZED_NAME_HAS_MORE = "has_more";
  @SerializedName(SERIALIZED_NAME_HAS_MORE)
  @javax.annotation.Nullable
  private Boolean hasMore;

  public static final String SERIALIZED_NAME_META = "meta";
  @SerializedName(SERIALIZED_NAME_META)
  @javax.annotation.Nullable
  private Pagination meta;

  public static final String SERIALIZED_NAME_NEXT_SINCE = "next_since";
  @SerializedName(SERIALIZED_NAME_NEXT_SINCE)
  @javax.annotation.Nullable
  private String nextSince;

  public static final String SERIALIZED_NAME_TECHNICIANS = "technicians";
  @SerializedName(SERIALIZED_NAME_TECHNICIANS)
  @javax.annotation.Nullable
  private List<Technician> technicians = new ArrayList<>();

  public TechnicianList() {
  }

  public TechnicianList hasMore(@javax.annotation.Nullable Boolean hasMore) {
    this.hasMore = hasMore;
    return this;
  }

  /**
   * True if more rows exist beyond this page.
   * @return hasMore
   */
  @javax.annotation.Nullable
  public Boolean getHasMore() {
    return hasMore;
  }

  public void setHasMore(@javax.annotation.Nullable Boolean hasMore) {
    this.hasMore = hasMore;
  }


  public TechnicianList meta(@javax.annotation.Nullable Pagination meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Page/limit/total pagination metadata.
   * @return meta
   */
  @javax.annotation.Nullable
  public Pagination getMeta() {
    return meta;
  }

  public void setMeta(@javax.annotation.Nullable Pagination meta) {
    this.meta = meta;
  }


  public TechnicianList nextSince(@javax.annotation.Nullable String nextSince) {
    this.nextSince = nextSince;
    return this;
  }

  /**
   * Cursor for short-polling: pass back as &#x60;since&#x60; to fetch only rows changed after this point (RFC3339).
   * @return nextSince
   */
  @javax.annotation.Nullable
  public String getNextSince() {
    return nextSince;
  }

  public void setNextSince(@javax.annotation.Nullable String nextSince) {
    this.nextSince = nextSince;
  }


  public TechnicianList technicians(@javax.annotation.Nullable List<Technician> technicians) {
    this.technicians = technicians;
    return this;
  }

  public TechnicianList addTechniciansItem(Technician techniciansItem) {
    if (this.technicians == null) {
      this.technicians = new ArrayList<>();
    }
    this.technicians.add(techniciansItem);
    return this;
  }

  /**
   * The technicians on this page.
   * @return technicians
   */
  @javax.annotation.Nullable
  public List<Technician> getTechnicians() {
    return technicians;
  }

  public void setTechnicians(@javax.annotation.Nullable List<Technician> technicians) {
    this.technicians = technicians;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TechnicianList technicianList = (TechnicianList) o;
    return Objects.equals(this.hasMore, technicianList.hasMore) &&
        Objects.equals(this.meta, technicianList.meta) &&
        Objects.equals(this.nextSince, technicianList.nextSince) &&
        Objects.equals(this.technicians, technicianList.technicians);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasMore, meta, nextSince, technicians);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TechnicianList {\n");
    sb.append("    hasMore: ").append(toIndentedString(hasMore)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    nextSince: ").append(toIndentedString(nextSince)).append("\n");
    sb.append("    technicians: ").append(toIndentedString(technicians)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("has_more");
    openapiFields.add("meta");
    openapiFields.add("next_since");
    openapiFields.add("technicians");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TechnicianList
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TechnicianList.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TechnicianList is not found in the empty JSON string", TechnicianList.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TechnicianList.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TechnicianList` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `meta`
      if (jsonObj.get("meta") != null && !jsonObj.get("meta").isJsonNull()) {
        Pagination.validateJsonElement(jsonObj.get("meta"));
      }
      if ((jsonObj.get("next_since") != null && !jsonObj.get("next_since").isJsonNull()) && !jsonObj.get("next_since").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `next_since` to be a primitive type in the JSON string but got `%s`", jsonObj.get("next_since").toString()));
      }
      if (jsonObj.get("technicians") != null && !jsonObj.get("technicians").isJsonNull()) {
        JsonArray jsonArraytechnicians = jsonObj.getAsJsonArray("technicians");
        if (jsonArraytechnicians != null) {
          // ensure the json data is an array
          if (!jsonObj.get("technicians").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `technicians` to be an array in the JSON string but got `%s`", jsonObj.get("technicians").toString()));
          }

          // validate the optional field `technicians` (array)
          for (int i = 0; i < jsonArraytechnicians.size(); i++) {
            Technician.validateJsonElement(jsonArraytechnicians.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TechnicianList.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TechnicianList' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TechnicianList> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TechnicianList.class));

       return (TypeAdapter<T>) new TypeAdapter<TechnicianList>() {
           @Override
           public void write(JsonWriter out, TechnicianList value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TechnicianList read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TechnicianList given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TechnicianList
   * @throws IOException if the JSON string is invalid with respect to TechnicianList
   */
  public static TechnicianList fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TechnicianList.class);
  }

  /**
   * Convert an instance of TechnicianList to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

