/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.model;

import java.util.Objects;
import com.crisphive.client.model.ApiInternalTechtimeoffActions;
import com.crisphive.client.model.ApiInternalTechtimeoffStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.crisphive.client.JSON;

/**
 * TechnicianTimeOff
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class TechnicianTimeOff {
  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  @javax.annotation.Nullable
  private ApiInternalTechtimeoffActions actions;

  public static final String SERIALIZED_NAME_BUSINESS_ID = "business_id";
  @SerializedName(SERIALIZED_NAME_BUSINESS_ID)
  @javax.annotation.Nullable
  private UUID businessId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_DELETED_AT = "deleted_at";
  @SerializedName(SERIALIZED_NAME_DELETED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String SERIALIZED_NAME_END_DATETIME = "end_datetime";
  @SerializedName(SERIALIZED_NAME_END_DATETIME)
  @javax.annotation.Nullable
  private OffsetDateTime endDatetime;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private UUID id;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  @javax.annotation.Nullable
  private String reason;

  public static final String SERIALIZED_NAME_START_DATETIME = "start_datetime";
  @SerializedName(SERIALIZED_NAME_START_DATETIME)
  @javax.annotation.Nullable
  private OffsetDateTime startDatetime;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private ApiInternalTechtimeoffStatus status;

  public static final String SERIALIZED_NAME_TECHNICIAN_ID = "technician_id";
  @SerializedName(SERIALIZED_NAME_TECHNICIAN_ID)
  @javax.annotation.Nullable
  private UUID technicianId;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public TechnicianTimeOff() {
  }

  public TechnicianTimeOff actions(@javax.annotation.Nullable ApiInternalTechtimeoffActions actions) {
    this.actions = actions;
    return this;
  }

  /**
   * Which dashboard actions the caller may take on this record.
   * @return actions
   */
  @javax.annotation.Nullable
  public ApiInternalTechtimeoffActions getActions() {
    return actions;
  }

  public void setActions(@javax.annotation.Nullable ApiInternalTechtimeoffActions actions) {
    this.actions = actions;
  }


  public TechnicianTimeOff businessId(@javax.annotation.Nullable UUID businessId) {
    this.businessId = businessId;
    return this;
  }

  /**
   * Owning business.
   * @return businessId
   */
  @javax.annotation.Nullable
  public UUID getBusinessId() {
    return businessId;
  }

  public void setBusinessId(@javax.annotation.Nullable UUID businessId) {
    this.businessId = businessId;
  }


  public TechnicianTimeOff createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TechnicianTimeOff deletedAt(@javax.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(@javax.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public TechnicianTimeOff endDatetime(@javax.annotation.Nullable OffsetDateTime endDatetime) {
    this.endDatetime = endDatetime;
    return this;
  }

  /**
   * Block end (RFC3339 instant, UTC).
   * @return endDatetime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEndDatetime() {
    return endDatetime;
  }

  public void setEndDatetime(@javax.annotation.Nullable OffsetDateTime endDatetime) {
    this.endDatetime = endDatetime;
  }


  public TechnicianTimeOff id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * UUID of the record.
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public TechnicianTimeOff reason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Free-text reason.
   * @return reason
   */
  @javax.annotation.Nullable
  public String getReason() {
    return reason;
  }

  public void setReason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
  }


  public TechnicianTimeOff startDatetime(@javax.annotation.Nullable OffsetDateTime startDatetime) {
    this.startDatetime = startDatetime;
    return this;
  }

  /**
   * Block start (RFC3339 instant, UTC).
   * @return startDatetime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getStartDatetime() {
    return startDatetime;
  }

  public void setStartDatetime(@javax.annotation.Nullable OffsetDateTime startDatetime) {
    this.startDatetime = startDatetime;
  }


  public TechnicianTimeOff status(@javax.annotation.Nullable ApiInternalTechtimeoffStatus status) {
    this.status = status;
    return this;
  }

  /**
   * pending (awaiting approval — the engine does NOT honour it yet) | approved (blocks scheduling) | rejected | cancelled.
   * @return status
   */
  @javax.annotation.Nullable
  public ApiInternalTechtimeoffStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable ApiInternalTechtimeoffStatus status) {
    this.status = status;
  }


  public TechnicianTimeOff technicianId(@javax.annotation.Nullable UUID technicianId) {
    this.technicianId = technicianId;
    return this;
  }

  /**
   * The technician the block belongs to.
   * @return technicianId
   */
  @javax.annotation.Nullable
  public UUID getTechnicianId() {
    return technicianId;
  }

  public void setTechnicianId(@javax.annotation.Nullable UUID technicianId) {
    this.technicianId = technicianId;
  }


  public TechnicianTimeOff updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TechnicianTimeOff technicianTimeOff = (TechnicianTimeOff) o;
    return Objects.equals(this.actions, technicianTimeOff.actions) &&
        Objects.equals(this.businessId, technicianTimeOff.businessId) &&
        Objects.equals(this.createdAt, technicianTimeOff.createdAt) &&
        Objects.equals(this.deletedAt, technicianTimeOff.deletedAt) &&
        Objects.equals(this.endDatetime, technicianTimeOff.endDatetime) &&
        Objects.equals(this.id, technicianTimeOff.id) &&
        Objects.equals(this.reason, technicianTimeOff.reason) &&
        Objects.equals(this.startDatetime, technicianTimeOff.startDatetime) &&
        Objects.equals(this.status, technicianTimeOff.status) &&
        Objects.equals(this.technicianId, technicianTimeOff.technicianId) &&
        Objects.equals(this.updatedAt, technicianTimeOff.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actions, businessId, createdAt, deletedAt, endDatetime, id, reason, startDatetime, status, technicianId, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TechnicianTimeOff {\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    businessId: ").append(toIndentedString(businessId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    endDatetime: ").append(toIndentedString(endDatetime)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    startDatetime: ").append(toIndentedString(startDatetime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    technicianId: ").append(toIndentedString(technicianId)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("actions");
    openapiFields.add("business_id");
    openapiFields.add("created_at");
    openapiFields.add("deleted_at");
    openapiFields.add("end_datetime");
    openapiFields.add("id");
    openapiFields.add("reason");
    openapiFields.add("start_datetime");
    openapiFields.add("status");
    openapiFields.add("technician_id");
    openapiFields.add("updated_at");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TechnicianTimeOff
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TechnicianTimeOff.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TechnicianTimeOff is not found in the empty JSON string", TechnicianTimeOff.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TechnicianTimeOff.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TechnicianTimeOff` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `actions`
      if (jsonObj.get("actions") != null && !jsonObj.get("actions").isJsonNull()) {
        ApiInternalTechtimeoffActions.validateJsonElement(jsonObj.get("actions"));
      }
      if ((jsonObj.get("business_id") != null && !jsonObj.get("business_id").isJsonNull()) && !jsonObj.get("business_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `business_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("business_id").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonNull()) && !jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        ApiInternalTechtimeoffStatus.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("technician_id") != null && !jsonObj.get("technician_id").isJsonNull()) && !jsonObj.get("technician_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `technician_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("technician_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TechnicianTimeOff.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TechnicianTimeOff' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TechnicianTimeOff> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TechnicianTimeOff.class));

       return (TypeAdapter<T>) new TypeAdapter<TechnicianTimeOff>() {
           @Override
           public void write(JsonWriter out, TechnicianTimeOff value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TechnicianTimeOff read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TechnicianTimeOff given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TechnicianTimeOff
   * @throws IOException if the JSON string is invalid with respect to TechnicianTimeOff
   */
  public static TechnicianTimeOff fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TechnicianTimeOff.class);
  }

  /**
   * Convert an instance of TechnicianTimeOff to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

