/*
 * Crisphive Developer API
 * Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.crisphive.client.api;

import com.crisphive.client.ApiCallback;
import com.crisphive.client.ApiClient;
import com.crisphive.client.ApiException;
import com.crisphive.client.ApiResponse;
import com.crisphive.client.Configuration;
import com.crisphive.client.Pair;
import com.crisphive.client.ProgressRequestBody;
import com.crisphive.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.crisphive.client.model.CreateJobType200Response;
import com.crisphive.client.model.GetJobType200Response;
import com.crisphive.client.model.JobTypeCreateRequest;
import com.crisphive.client.model.JobTypeUpdateRequest;
import com.crisphive.client.model.ListJobTypes200Response;
import com.crisphive.client.model.ResponseEnvelope;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class JobTypesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public JobTypesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public JobTypesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for createJobType
     * @param jobTypeCreateRequest Job type (required)
     * @param idempotencyKey Unique key making retries safe: a repeat send with the same key replays the original response (header Idempotent-Replayed: true) instead of re-running the operation. Reusing a key with a different body returns 422 IDEMPOTENCY_KEY_REUSE. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY | JOB_TYPE_INVALID_NAME | JOB_TYPE_INVALID_STATUS | JOB_TYPE_INVALID_DEFAULT_DURATION </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> JOB_TYPE_DUPLICATE </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createJobTypeCall(JobTypeCreateRequest jobTypeCreateRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = jobTypeCreateRequest;

        // create path and map variables
        String localVarPath = "/job-types";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createJobTypeValidateBeforeCall(JobTypeCreateRequest jobTypeCreateRequest, String idempotencyKey, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'jobTypeCreateRequest' is set
        if (jobTypeCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'jobTypeCreateRequest' when calling createJobType(Async)");
        }

        return createJobTypeCall(jobTypeCreateRequest, idempotencyKey, _callback);

    }

    /**
     * Add a job type to the catalog
     * Creates a kind of work customers can book, such as \&quot;Annual boiler service\&quot; or \&quot;Drain unblocking\&quot;. Job types classify bookings: createJobRequest takes an optional &#x60;job_type_id&#x60; from this catalog and the job keeps the type&#39;s name as it was at booking time.  &#x60;name&#x60; is the only required field and must be unique in the business (JOB_TYPE_DUPLICATE). &#x60;status&#x60; defaults to active. An inactive type stays in the catalog but cannot be chosen for new job requests; use that rather than deleting a type you may revive.  Send an Idempotency-Key header (the &#x60;idempotency_key&#x60; argument over MCP) so a retried call replays the original response instead of creating a duplicate type.  Optional default_duration_minutes (+ default_mobilization_minutes / default_demobilization_minutes) set how long this kind of work usually takes: quoteJobRequest uses them when it is sent no job_duration_minutes, so an automation or voice agent can schedule the job without knowing the length. A buffer needs a duration (JOB_TYPE_INVALID_DEFAULT_DURATION).  This defines the catalog, not a booking. To book actual work use createJobRequest and reference the job type there.
     * @param jobTypeCreateRequest Job type (required)
     * @param idempotencyKey Unique key making retries safe: a repeat send with the same key replays the original response (header Idempotent-Replayed: true) instead of re-running the operation. Reusing a key with a different body returns 422 IDEMPOTENCY_KEY_REUSE. (optional)
     * @return CreateJobType200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY | JOB_TYPE_INVALID_NAME | JOB_TYPE_INVALID_STATUS | JOB_TYPE_INVALID_DEFAULT_DURATION </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> JOB_TYPE_DUPLICATE </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public CreateJobType200Response createJobType(JobTypeCreateRequest jobTypeCreateRequest, String idempotencyKey) throws ApiException {
        ApiResponse<CreateJobType200Response> localVarResp = createJobTypeWithHttpInfo(jobTypeCreateRequest, idempotencyKey);
        return localVarResp.getData();
    }

    /**
     * Add a job type to the catalog
     * Creates a kind of work customers can book, such as \&quot;Annual boiler service\&quot; or \&quot;Drain unblocking\&quot;. Job types classify bookings: createJobRequest takes an optional &#x60;job_type_id&#x60; from this catalog and the job keeps the type&#39;s name as it was at booking time.  &#x60;name&#x60; is the only required field and must be unique in the business (JOB_TYPE_DUPLICATE). &#x60;status&#x60; defaults to active. An inactive type stays in the catalog but cannot be chosen for new job requests; use that rather than deleting a type you may revive.  Send an Idempotency-Key header (the &#x60;idempotency_key&#x60; argument over MCP) so a retried call replays the original response instead of creating a duplicate type.  Optional default_duration_minutes (+ default_mobilization_minutes / default_demobilization_minutes) set how long this kind of work usually takes: quoteJobRequest uses them when it is sent no job_duration_minutes, so an automation or voice agent can schedule the job without knowing the length. A buffer needs a duration (JOB_TYPE_INVALID_DEFAULT_DURATION).  This defines the catalog, not a booking. To book actual work use createJobRequest and reference the job type there.
     * @param jobTypeCreateRequest Job type (required)
     * @param idempotencyKey Unique key making retries safe: a repeat send with the same key replays the original response (header Idempotent-Replayed: true) instead of re-running the operation. Reusing a key with a different body returns 422 IDEMPOTENCY_KEY_REUSE. (optional)
     * @return ApiResponse&lt;CreateJobType200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY | JOB_TYPE_INVALID_NAME | JOB_TYPE_INVALID_STATUS | JOB_TYPE_INVALID_DEFAULT_DURATION </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> JOB_TYPE_DUPLICATE </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CreateJobType200Response> createJobTypeWithHttpInfo(JobTypeCreateRequest jobTypeCreateRequest, String idempotencyKey) throws ApiException {
        okhttp3.Call localVarCall = createJobTypeValidateBeforeCall(jobTypeCreateRequest, idempotencyKey, null);
        Type localVarReturnType = new TypeToken<CreateJobType200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add a job type to the catalog (asynchronously)
     * Creates a kind of work customers can book, such as \&quot;Annual boiler service\&quot; or \&quot;Drain unblocking\&quot;. Job types classify bookings: createJobRequest takes an optional &#x60;job_type_id&#x60; from this catalog and the job keeps the type&#39;s name as it was at booking time.  &#x60;name&#x60; is the only required field and must be unique in the business (JOB_TYPE_DUPLICATE). &#x60;status&#x60; defaults to active. An inactive type stays in the catalog but cannot be chosen for new job requests; use that rather than deleting a type you may revive.  Send an Idempotency-Key header (the &#x60;idempotency_key&#x60; argument over MCP) so a retried call replays the original response instead of creating a duplicate type.  Optional default_duration_minutes (+ default_mobilization_minutes / default_demobilization_minutes) set how long this kind of work usually takes: quoteJobRequest uses them when it is sent no job_duration_minutes, so an automation or voice agent can schedule the job without knowing the length. A buffer needs a duration (JOB_TYPE_INVALID_DEFAULT_DURATION).  This defines the catalog, not a booking. To book actual work use createJobRequest and reference the job type there.
     * @param jobTypeCreateRequest Job type (required)
     * @param idempotencyKey Unique key making retries safe: a repeat send with the same key replays the original response (header Idempotent-Replayed: true) instead of re-running the operation. Reusing a key with a different body returns 422 IDEMPOTENCY_KEY_REUSE. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY | JOB_TYPE_INVALID_NAME | JOB_TYPE_INVALID_STATUS | JOB_TYPE_INVALID_DEFAULT_DURATION </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> JOB_TYPE_DUPLICATE </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createJobTypeAsync(JobTypeCreateRequest jobTypeCreateRequest, String idempotencyKey, final ApiCallback<CreateJobType200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = createJobTypeValidateBeforeCall(jobTypeCreateRequest, idempotencyKey, _callback);
        Type localVarReturnType = new TypeToken<CreateJobType200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deleteJobType
     * @param id Job Type ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> JOB_TYPE_SYSTEM_READ_ONLY </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteJobTypeCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/job-types/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteJobTypeValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteJobType(Async)");
        }

        return deleteJobTypeCall(id, _callback);

    }

    /**
     * Remove a job type from the catalog
     * Soft-deletes the entry: it disappears from the catalog and can no longer be selected for new bookings. Jobs already booked against it are unaffected and keep showing the name they were booked with.  Prefer updateJobType with &#x60;status&#x3D;inactive&#x60; in almost every case: it has the same effect on the booking form and is trivially reversible. Delete is for a type created in error or one that will never return.  Rows the platform ships with (&#x60;is_system&#x3D;true&#x60;) cannot be deleted and are refused with JOB_TYPE_SYSTEM_READ_ONLY.
     * @param id Job Type ID (required)
     * @return ResponseEnvelope
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> JOB_TYPE_SYSTEM_READ_ONLY </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public ResponseEnvelope deleteJobType(String id) throws ApiException {
        ApiResponse<ResponseEnvelope> localVarResp = deleteJobTypeWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Remove a job type from the catalog
     * Soft-deletes the entry: it disappears from the catalog and can no longer be selected for new bookings. Jobs already booked against it are unaffected and keep showing the name they were booked with.  Prefer updateJobType with &#x60;status&#x3D;inactive&#x60; in almost every case: it has the same effect on the booking form and is trivially reversible. Delete is for a type created in error or one that will never return.  Rows the platform ships with (&#x60;is_system&#x3D;true&#x60;) cannot be deleted and are refused with JOB_TYPE_SYSTEM_READ_ONLY.
     * @param id Job Type ID (required)
     * @return ApiResponse&lt;ResponseEnvelope&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> JOB_TYPE_SYSTEM_READ_ONLY </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ResponseEnvelope> deleteJobTypeWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = deleteJobTypeValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<ResponseEnvelope>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Remove a job type from the catalog (asynchronously)
     * Soft-deletes the entry: it disappears from the catalog and can no longer be selected for new bookings. Jobs already booked against it are unaffected and keep showing the name they were booked with.  Prefer updateJobType with &#x60;status&#x3D;inactive&#x60; in almost every case: it has the same effect on the booking form and is trivially reversible. Delete is for a type created in error or one that will never return.  Rows the platform ships with (&#x60;is_system&#x3D;true&#x60;) cannot be deleted and are refused with JOB_TYPE_SYSTEM_READ_ONLY.
     * @param id Job Type ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> JOB_TYPE_SYSTEM_READ_ONLY </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteJobTypeAsync(String id, final ApiCallback<ResponseEnvelope> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteJobTypeValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<ResponseEnvelope>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getJobType
     * @param id Job Type ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getJobTypeCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/job-types/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getJobTypeValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getJobType(Async)");
        }

        return getJobTypeCall(id, _callback);

    }

    /**
     * Get a job type
     * Returns one entry of the business&#39;s service catalog (job/work-order type) with its localized display name — e.g. an HVAC tune-up, drain cleaning or electrical inspection offering.
     * @param id Job Type ID (required)
     * @return GetJobType200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public GetJobType200Response getJobType(String id) throws ApiException {
        ApiResponse<GetJobType200Response> localVarResp = getJobTypeWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get a job type
     * Returns one entry of the business&#39;s service catalog (job/work-order type) with its localized display name — e.g. an HVAC tune-up, drain cleaning or electrical inspection offering.
     * @param id Job Type ID (required)
     * @return ApiResponse&lt;GetJobType200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetJobType200Response> getJobTypeWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getJobTypeValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<GetJobType200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a job type (asynchronously)
     * Returns one entry of the business&#39;s service catalog (job/work-order type) with its localized display name — e.g. an HVAC tune-up, drain cleaning or electrical inspection offering.
     * @param id Job Type ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getJobTypeAsync(String id, final ApiCallback<GetJobType200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = getJobTypeValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<GetJobType200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listJobTypes
     * @param status Filter by status (active|inactive) (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listJobTypesCall(String status, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/job-types";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (status != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status", status));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listJobTypesValidateBeforeCall(String status, final ApiCallback _callback) throws ApiException {
        return listJobTypesCall(status, _callback);

    }

    /**
     * List job types
     * Returns the business&#39;s service catalog — the job/work-order types it offers (e.g. installation, repair, maintenance, inspection for trades like HVAC, plumbing, electrical, cleaning). Use it to discover the &#x60;job_type_id&#x60; accepted when booking a job request, or to render a services menu on your own site.
     * @param status Filter by status (active|inactive) (optional)
     * @return ListJobTypes200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public ListJobTypes200Response listJobTypes(String status) throws ApiException {
        ApiResponse<ListJobTypes200Response> localVarResp = listJobTypesWithHttpInfo(status);
        return localVarResp.getData();
    }

    /**
     * List job types
     * Returns the business&#39;s service catalog — the job/work-order types it offers (e.g. installation, repair, maintenance, inspection for trades like HVAC, plumbing, electrical, cleaning). Use it to discover the &#x60;job_type_id&#x60; accepted when booking a job request, or to render a services menu on your own site.
     * @param status Filter by status (active|inactive) (optional)
     * @return ApiResponse&lt;ListJobTypes200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ListJobTypes200Response> listJobTypesWithHttpInfo(String status) throws ApiException {
        okhttp3.Call localVarCall = listJobTypesValidateBeforeCall(status, null);
        Type localVarReturnType = new TypeToken<ListJobTypes200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List job types (asynchronously)
     * Returns the business&#39;s service catalog — the job/work-order types it offers (e.g. installation, repair, maintenance, inspection for trades like HVAC, plumbing, electrical, cleaning). Use it to discover the &#x60;job_type_id&#x60; accepted when booking a job request, or to render a services menu on your own site.
     * @param status Filter by status (active|inactive) (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> API_KEY_SCOPE_INSUFFICIENT — the key authenticated but is restricted and does not carry the permission this endpoint requires. data.required_scope names the missing permission code. Mint a key that carries it (a full-access key carries all of them); this is NOT the same as your user account lacking a permission.  PLAN_MODULE_NOT_INCLUDED — the business&#39;s subscription plan does not include the module this endpoint belongs to. data.module names it. This is a BILLING answer, not a credential one: no key, however broad, can reach a module the plan excludes — the business has to upgrade. Distinguish it from API_KEY_SCOPE_INSUFFICIENT by error_code, never by status. </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listJobTypesAsync(String status, final ApiCallback<ListJobTypes200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = listJobTypesValidateBeforeCall(status, _callback);
        Type localVarReturnType = new TypeToken<ListJobTypes200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateJobType
     * @param id Job Type ID (required)
     * @param jobTypeUpdateRequest Job type (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY | JOB_TYPE_INVALID_NAME | JOB_TYPE_INVALID_STATUS | JOB_TYPE_INVALID_DEFAULT_DURATION </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> JOB_TYPE_SYSTEM_READ_ONLY </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> JOB_TYPE_DUPLICATE </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateJobTypeCall(String id, JobTypeUpdateRequest jobTypeUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = jobTypeUpdateRequest;

        // create path and map variables
        String localVarPath = "/job-types/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateJobTypeValidateBeforeCall(String id, JobTypeUpdateRequest jobTypeUpdateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateJobType(Async)");
        }

        // verify the required parameter 'jobTypeUpdateRequest' is set
        if (jobTypeUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'jobTypeUpdateRequest' when calling updateJobType(Async)");
        }

        return updateJobTypeCall(id, jobTypeUpdateRequest, _callback);

    }

    /**
     * Rename a job type or change its availability
     * Edits a catalog entry in place. A rename applies to NEW bookings only: every job stores the job-type name it was booked with, so existing and completed jobs keep their original label.  Partial update: omit a field to keep it. &#x60;name&#x60; rejects \&quot;\&quot; because a type must stay identifiable, and must stay unique (JOB_TYPE_DUPLICATE). Setting &#x60;status&#x60; to inactive is the reversible way to take a type off the booking form; inactive types are refused for new job requests.  Default quote bundle: default_duration_minutes / default_mobilization_minutes / default_demobilization_minutes follow the same partial rule; omit to keep, 0 to clear, a value to set. Clearing the duration while a buffer stays is refused (JOB_TYPE_INVALID_DEFAULT_DURATION).  Rows the platform ships with (&#x60;is_system&#x3D;true&#x60;, e.g. the default \&quot;General\&quot; type) keep their name and status read-only (JOB_TYPE_SYSTEM_READ_ONLY); their default quote bundle IS editable. Create your own type if you need different wording.
     * @param id Job Type ID (required)
     * @param jobTypeUpdateRequest Job type (required)
     * @return ResponseEnvelope
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY | JOB_TYPE_INVALID_NAME | JOB_TYPE_INVALID_STATUS | JOB_TYPE_INVALID_DEFAULT_DURATION </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> JOB_TYPE_SYSTEM_READ_ONLY </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> JOB_TYPE_DUPLICATE </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public ResponseEnvelope updateJobType(String id, JobTypeUpdateRequest jobTypeUpdateRequest) throws ApiException {
        ApiResponse<ResponseEnvelope> localVarResp = updateJobTypeWithHttpInfo(id, jobTypeUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * Rename a job type or change its availability
     * Edits a catalog entry in place. A rename applies to NEW bookings only: every job stores the job-type name it was booked with, so existing and completed jobs keep their original label.  Partial update: omit a field to keep it. &#x60;name&#x60; rejects \&quot;\&quot; because a type must stay identifiable, and must stay unique (JOB_TYPE_DUPLICATE). Setting &#x60;status&#x60; to inactive is the reversible way to take a type off the booking form; inactive types are refused for new job requests.  Default quote bundle: default_duration_minutes / default_mobilization_minutes / default_demobilization_minutes follow the same partial rule; omit to keep, 0 to clear, a value to set. Clearing the duration while a buffer stays is refused (JOB_TYPE_INVALID_DEFAULT_DURATION).  Rows the platform ships with (&#x60;is_system&#x3D;true&#x60;, e.g. the default \&quot;General\&quot; type) keep their name and status read-only (JOB_TYPE_SYSTEM_READ_ONLY); their default quote bundle IS editable. Create your own type if you need different wording.
     * @param id Job Type ID (required)
     * @param jobTypeUpdateRequest Job type (required)
     * @return ApiResponse&lt;ResponseEnvelope&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY | JOB_TYPE_INVALID_NAME | JOB_TYPE_INVALID_STATUS | JOB_TYPE_INVALID_DEFAULT_DURATION </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> JOB_TYPE_SYSTEM_READ_ONLY </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> JOB_TYPE_DUPLICATE </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ResponseEnvelope> updateJobTypeWithHttpInfo(String id, JobTypeUpdateRequest jobTypeUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = updateJobTypeValidateBeforeCall(id, jobTypeUpdateRequest, null);
        Type localVarReturnType = new TypeToken<ResponseEnvelope>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Rename a job type or change its availability (asynchronously)
     * Edits a catalog entry in place. A rename applies to NEW bookings only: every job stores the job-type name it was booked with, so existing and completed jobs keep their original label.  Partial update: omit a field to keep it. &#x60;name&#x60; rejects \&quot;\&quot; because a type must stay identifiable, and must stay unique (JOB_TYPE_DUPLICATE). Setting &#x60;status&#x60; to inactive is the reversible way to take a type off the booking form; inactive types are refused for new job requests.  Default quote bundle: default_duration_minutes / default_mobilization_minutes / default_demobilization_minutes follow the same partial rule; omit to keep, 0 to clear, a value to set. Clearing the duration while a buffer stays is refused (JOB_TYPE_INVALID_DEFAULT_DURATION).  Rows the platform ships with (&#x60;is_system&#x3D;true&#x60;, e.g. the default \&quot;General\&quot; type) keep their name and status read-only (JOB_TYPE_SYSTEM_READ_ONLY); their default quote bundle IS editable. Create your own type if you need different wording.
     * @param id Job Type ID (required)
     * @param jobTypeUpdateRequest Job type (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> INVALID_REQUEST_BODY | JOB_TYPE_INVALID_NAME | JOB_TYPE_INVALID_STATUS | JOB_TYPE_INVALID_DEFAULT_DURATION </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> UNAUTHORIZED </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> JOB_TYPE_SYSTEM_READ_ONLY </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> JOB_TYPE_NOT_FOUND </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> JOB_TYPE_DUPLICATE </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> TOO_MANY_REQUESTS — per-key rate limit exceeded (240 requests/min, shared across /v1 and /mcp). Back off for the number of seconds in the Retry-After header; every response also carries X-RateLimit-Limit / X-RateLimit-Remaining / X-RateLimit-Reset. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateJobTypeAsync(String id, JobTypeUpdateRequest jobTypeUpdateRequest, final ApiCallback<ResponseEnvelope> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateJobTypeValidateBeforeCall(id, jobTypeUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<ResponseEnvelope>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
